DROP PROFILE PBM_CDW_PROFILE CASCADE;

CREATE PROFILE PBM_CDW_PROFILE LIMIT
  SESSIONS_PER_USER 3
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME 600
  IDLE_TIME 30
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LIFE_TIME 1095
  PASSWORD_REUSE_TIME 732
  PASSWORD_REUSE_MAX 3
  PASSWORD_LOCK_TIME 0.0006
  PASSWORD_GRACE_TIME 10
  PASSWORD_VERIFY_FUNCTION VERIFY_FUNCTION_11G;
