DROP USER ERX_READ_USER CASCADE;

CREATE USER ERX_READ_USER
  IDENTIFIED BY &pwd
  DEFAULT TABLESPACE ERX_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE SERVICE_ACCOUNT_PROFILE
  ACCOUNT UNLOCK;
  -- 2 Roles for ERX_READ_USER 
  GRANT CONNECT TO ERX_READ_USER;
  GRANT ERX_READ_ROLE TO ERX_READ_USER;
  ALTER USER ERX_READ_USER DEFAULT ROLE ALL;
  -- 1 System Privilege for ERX_READ_USER 
  GRANT UNLIMITED TABLESPACE TO ERX_READ_USER;