-- execute after both erx and pdi schema setup is complete and roles/role grants are complete

GRANT PDI_READ_ROLE        TO ERX_READ_USER;
GRANT PDI_UPDATE_ROLE      TO ERX_UPDATE_USER;
GRANT ERX_READ_ROLE        TO ERX_READ_USER;
GRANT ERX_UPDATE_ROLE      TO ERX_UPDATE_USER;

ALTER USER ERX_READ_USER   DEFAULT ROLE ALL;
ALTER USER ERX_UPDATE_USER DEFAULT ROLE ALL;
