--new table to store component status and updates
DROP TABLE ERX.MONITORING;

CREATE TABLE ERX.MONITORING 
(
  MONITORING_ID NUMBER NOT NULL 
, MVI_STATUS VARCHAR2(50) NOT NULL
, EANDE_STATUS VARCHAR2(50) NOT NULL
, PDI_INB_JOB_STATUS VARCHAR2(50) NOT NULL
, PDI_OUTB_JOB VARCHAR2(50) NOT NULL
, PDI_TOVISTA_JOB VARCHAR2(50) NOT NULL
, DAS_STATUS VARCHAR2(50) NOT NULL
, CREATED_DATE DATE NOT NULL
, CONSTRAINT MONITORING_PK PRIMARY KEY 
  (
    MONITORING_ID 
  )
  ENABLE 
);