--needs to be run by privileged user 
--prompts for password to be entered

DROP USER PDI4 CASCADE;

CREATE USER PDI4
  IDENTIFIED BY &pwd
  DEFAULT TABLESPACE ERX_DATA
  TEMPORARY TABLESPACE TEMP;
  
 
  ACCOUNT UNLOCK;
  GRANT CONNECT TO PDI4;
  GRANT RESOURCE TO PDI4;
  ALTER USER PDI4 DEFAULT ROLE ALL;
  GRANT UNLIMITED TABLESPACE TO PDI4;
