DROP TABLE PDI4.R_CONDITION
;

CREATE TABLE PDI4.R_CONDITION
(
  ID_CONDITION INTEGER
, ID_CONDITION_PARENT INTEGER
, NEGATED CHAR(1)
, OPERATOR VARCHAR2(255)
, LEFT_NAME VARCHAR2(255)
, CONDITION_FUNCTION VARCHAR2(255)
, RIGHT_NAME VARCHAR2(255)
, ID_VALUE_RIGHT INTEGER
, PRIMARY KEY (ID_CONDITION)
)
;