DROP TABLE PDI4.R_DATABASE_ATTRIBUTE
;

CREATE TABLE PDI4.R_DATABASE_ATTRIBUTE
(
  ID_DATABASE_ATTRIBUTE INTEGER
, ID_DATABASE INTEGER
, CODE VARCHAR2(255)
, VALUE_STR CLOB
, PRIMARY KEY (ID_DATABASE_ATTRIBUTE)
)
;

CREATE UNIQUE INDEX IDX_4_RDAT ON PDI4.R_DATABASE_ATTRIBUTE(ID_DATABASE, CODE)
;