DROP TABLE PDI4.R_DATABASE_CONTYPE
;

CREATE TABLE PDI4.R_DATABASE_CONTYPE
(
  ID_DATABASE_CONTYPE INTEGER
, CODE VARCHAR2(255)
, DESCRIPTION VARCHAR2(255)
, PRIMARY KEY (ID_DATABASE_CONTYPE)
)
;

INSERT INTO PDI4.R_DATABASE_CONTYPE(ID_DATABASE_CONTYPE, CODE, DESCRIPTION) VALUES (1,'Native','Native (JDBC)');

INSERT INTO PDI4.R_DATABASE_CONTYPE(ID_DATABASE_CONTYPE, CODE, DESCRIPTION) VALUES (2,'ODBC','ODBC');

INSERT INTO PDI4.R_DATABASE_CONTYPE(ID_DATABASE_CONTYPE, CODE, DESCRIPTION) VALUES (3,'OCI','OCI');

INSERT INTO PDI4.R_DATABASE_CONTYPE(ID_DATABASE_CONTYPE, CODE, DESCRIPTION) VALUES (4,'Plugin','Plugin specific access method');

INSERT INTO PDI4.R_DATABASE_CONTYPE(ID_DATABASE_CONTYPE, CODE, DESCRIPTION) VALUES (5,'JNDI','JNDI');

INSERT INTO PDI4.R_DATABASE_CONTYPE(ID_DATABASE_CONTYPE, CODE, DESCRIPTION) VALUES (6,',','Custom');