DROP TABLE PDI4.R_DATABASE_TYPE
;

CREATE TABLE PDI4.R_DATABASE_TYPE
(
  ID_DATABASE_TYPE INTEGER
, CODE VARCHAR2(255)
, DESCRIPTION VARCHAR2(255)
, PRIMARY KEY (ID_DATABASE_TYPE)
)
;

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (1,'INGRES','Ingres');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (2,'INTERBASE','Borland Interbase');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (3,'INFOBRIGHT','Infobright');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (4,'ORACLE','Oracle');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (5,'EXTENDB','ExtenDB');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (6,'MSACCESS','MS Access');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (7,'SYBASE','Sybase');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (8,'PALO','Palo MOLAP Server');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (9,'INFORMIX','Informix');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (10,'LucidDB','LucidDB');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (11,'TERADATA','Teradata');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (12,'UNIVERSE','UniVerse database');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (13,'MONETDB','MonetDB');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (14,'CACHE','Intersystems Cache');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (15,'MSSQL','MS SQL Server');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (16,'GREENPLUM','Greenplum');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (17,'GENERIC','Generic database');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (18,'SQLITE','SQLite');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (19,'REMEDY-AR-SYSTEM','Remedy Action Request System');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (20,'MONDRIAN','Native Mondrian');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (21,'NETEZZA','Netezza');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (22,'VERTICA5','Vertica 5+');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (23,'IMPALA','Impala');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (24,'POSTGRESQL','PostgreSQL');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (25,'EXASOL4','Exasol 4');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (26,'HYPERSONIC','Hypersonic');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (27,'AS/400','AS/400');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (28,'ORACLERDB','Oracle RDB');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (29,'DBASE','dBase III, IV or 5');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (30,'KINGBASEES','KingbaseES');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (31,'HIVE','Hadoop Hive');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (32,'SAPR3','SAP ERP System');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (33,'SQLBASE','Gupta SQL Base');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (34,'DERBY','Apache Derby');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (35,'VERTICA','Vertica');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (36,'INFINIDB','Calpont InfiniDB');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (37,'HIVE2','Hadoop Hive 2');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (38,'KettleThin','Pentaho Data Services');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (39,'MYSQL','MySQL');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (40,'MSSQLNATIVE','MS SQL Server (Native)');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (41,'H2','H2');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (42,'SAPDB','MaxDB (SAP DB)');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (43,'VECTORWISE','Ingres VectorWise');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (44,'DB2','IBM DB2');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (45,'NEOVIEW','Neoview');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (46,'IMPALASIMBA','Cloudera Impala');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (47,'SYBASEIQ','SybaseIQ');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (48,'REDSHIFT','Redshift');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (49,'FIREBIRD','Firebird SQL');

INSERT INTO PDI4.R_DATABASE_TYPE(ID_DATABASE_TYPE, CODE, DESCRIPTION) VALUES (50,'OpenERPDatabaseMeta','OpenERP Server');
