DROP TABLE PDI4.R_DEPENDENCY
;

CREATE TABLE PDI4.R_DEPENDENCY
(
  ID_DEPENDENCY INTEGER
, ID_TRANSFORMATION INTEGER
, ID_DATABASE INTEGER
, TABLE_NAME VARCHAR2(255)
, FIELD_NAME VARCHAR2(255)
, PRIMARY KEY (ID_DEPENDENCY)
)
;