DROP TABLE PDI4.R_DIRECTORY
;


CREATE TABLE PDI4.R_DIRECTORY
(
  ID_DIRECTORY INTEGER
, ID_DIRECTORY_PARENT INTEGER
, DIRECTORY_NAME VARCHAR2(255)
, PRIMARY KEY (ID_DIRECTORY)
)
;

CREATE UNIQUE INDEX IDX_4_RDIR ON PDI4.R_DIRECTORY(ID_DIRECTORY_PARENT, DIRECTORY_NAME)
;