DROP TABLE PDI4.R_JOB_ATTRIBUTE
;

CREATE TABLE PDI4.R_JOB_ATTRIBUTE
(
  ID_JOB_ATTRIBUTE INTEGER
, ID_JOB INTEGER
, NR INTEGER
, CODE VARCHAR2(255)
, VALUE_NUM INTEGER
, VALUE_STR CLOB
, PRIMARY KEY (ID_JOB_ATTRIBUTE)
)
;

CREATE UNIQUE INDEX IDX_4_JATT ON PDI4.R_JOB_ATTRIBUTE(ID_JOB, CODE, NR)
;