DROP TABLE PDI4.R_JOB
;

CREATE TABLE PDI4.R_JOB
(
  ID_JOB INTEGER
, ID_DIRECTORY INTEGER
, NAME VARCHAR2(255)
, DESCRIPTION CLOB
, EXTENDED_DESCRIPTION CLOB
, JOB_VERSION VARCHAR2(255)
, JOB_STATUS INTEGER
, ID_DATABASE_LOG INTEGER
, TABLE_NAME_LOG VARCHAR2(255)
, CREATED_USER VARCHAR2(255)
, CREATED_DATE DATE
, MODIFIED_USER VARCHAR2(255)
, MODIFIED_DATE DATE
, USE_BATCH_ID CHAR(1)
, PASS_BATCH_ID CHAR(1)
, USE_LOGFIELD CHAR(1)
, SHARED_FILE VARCHAR2(255)
, PRIMARY KEY (ID_JOB)
)
;