DROP TABLE PDI4.R_JOBENTRY_TYPE
;

CREATE TABLE PDI4.R_JOBENTRY_TYPE
(
  ID_JOBENTRY_TYPE INTEGER
, CODE VARCHAR2(255)
, DESCRIPTION VARCHAR2(255)
, PRIMARY KEY (ID_JOBENTRY_TYPE)
)
;

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (1,'WEBSERVICE_AVAILABLE','Check webservice availability');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (2,'MYSQL_BULK_FILE','BulkLoad from Mysql into file');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (3,'COPY_MOVE_RESULT_FILENAMES','Process result filenames');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (4,'XSD_VALIDATOR','XSD Validator');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (5,'SPECIAL','Special entries');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (6,'FILE_COMPARE','File Compare');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (7,'DataRefineryBuildModel','Build Model');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (8,'CREATE_FOLDER','Create a folder');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (9,'MAIL_VALIDATOR','Mail validator');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (10,'PALO_CUBE_DELETE','Palo Cube Delete');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (11,'DATASOURCE_PUBLISH','Publish Model');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (12,'MAIL','Mail');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (13,'TRUNCATE_TABLES','Truncate tables');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (14,'MSGBOX_INFO','Display Msgbox Info');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (15,'WAIT_FOR_SQL','Wait for SQL');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (16,'FTPS_GET','Get a file with FTPS');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (17,'FTP_DELETE','FTP Delete');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (18,'CHECK_FILES_LOCKED','Check files locked');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (19,'COLUMNS_EXIST','Columns exist in a table');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (20,'HadoopPigScriptExecutorPlugin','Pig Script Executor');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (21,'UNZIP','Unzip file');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (22,'JOB','Job');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (23,'DELETE_FILE','Delete file');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (24,'ABORT','Abort job');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (25,'SHELL','Shell');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (26,'HiveJobExecutorPlugin','Amazon Hive Job Executor');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (27,'XML_WELL_FORMED','Check if XML file is well formed');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (28,'SFTP','Get a file with SFTP');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (29,'HTTP','HTTP');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (30,'FTP_PUT','Put a file with FTP');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (31,'SQL','SQL');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (32,'HadoopCopyFilesPlugin','Hadoop Copy Files');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (33,'WRITE_TO_FILE','Write to file');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (34,'PGP_VERIFY_FILES','Verify file signature with PGP');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (35,'DOS_UNIX_CONVERTER','Convert file between Windows and Unix');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (36,'PGP_DECRYPT_FILES','Decrypt files with PGP');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (37,'EVAL','JavaScript');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (38,'TALEND_JOB_EXEC','Talend Job Execution');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (39,'DELAY','Wait for');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (40,'HL7MLLPAcknowledge','HL7 MLLP Acknowledge');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (41,'PALO_CUBE_CREATE','Palo Cube Create');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (42,'SparkSubmit','Spark Submit');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (43,'FTP','Get a file with FTP');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (44,'FOLDERS_COMPARE','Compare folders');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (45,'ZIP_FILE','Zip file');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (46,'GET_POP','Get mails (POP3/IMAP)');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (47,'TRANS','Transformation');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (48,'SEND_NAGIOS_PASSIVE_CHECK','Send Nagios passive check');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (49,'SET_VARIABLES','Set variables');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (50,'MS_ACCESS_BULK_LOAD','MS Access Bulk Load');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (51,'DummyJob','Example Job');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (52,'COPY_FILES','Copy Files');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (53,'EVAL_FILES_METRICS','Evaluate files metrics');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (54,'ADD_RESULT_FILENAMES','Add filenames to result');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (55,'PING','Ping a host');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (56,'CHECK_DB_CONNECTIONS','Check Db connections');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (57,'DELETE_FOLDERS','Delete folders');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (58,'FILE_EXISTS','File Exists');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (59,'EVAL_TABLE_CONTENT','Evaluate rows number in a table');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (60,'FILES_EXIST','Checks if files exist');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (61,'SFTPPUT','Put a file with SFTP');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (62,'DELETE_RESULT_FILENAMES','Delete filenames from result');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (63,'DELETE_FILES','Delete files');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (64,'FTPS_PUT','Upload files to FTPS');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (65,'PGP_ENCRYPT_FILES','Encrypt files with PGP');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (66,'HadoopTransJobExecutorPlugin','Pentaho MapReduce');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (67,'OozieJobExecutor','Oozie Job Executor');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (68,'SUCCESS','Success');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (69,'WAIT_FOR_FILE','Wait for file');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (70,'WRITE_TO_LOG','Write To Log');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (71,'MSSQL_BULK_LOAD','BulkLoad into MSSQL');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (72,'TELNET','Telnet a host');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (73,'MOVE_FILES','Move Files');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (74,'XSLT','XSL Transformation');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (75,'EMRJobExecutorPlugin','Amazon EMR Job Executor');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (76,'HadoopJobExecutorPlugin','Hadoop Job Executor ');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (77,'DTD_VALIDATOR','DTD Validator');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (78,'HL7MLLPInput','HL7 MLLP Input');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (79,'FOLDER_IS_EMPTY','Check if a folder is empty');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (80,'SIMPLE_EVAL','Simple evaluation');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (81,'SqoopExport','Sqoop Export');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (82,'EXPORT_REPOSITORY','Export repository to XML file');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (83,'SYSLOG','Send information using Syslog');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (84,'TABLE_EXISTS','Table exists');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (85,'MYSQL_BULK_LOAD','BulkLoad into Mysql');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (86,'CREATE_FILE','Create file');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (87,'SqoopImport','Sqoop Import');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (88,'CONNECTED_TO_REPOSITORY','Check if connected to repository');

INSERT INTO PDI4.R_JOBENTRY_TYPE(ID_JOBENTRY_TYPE, CODE, DESCRIPTION) VALUES (89,'SNMP_TRAP','Send SNMP trap');