DROP TABLE PDI4.R_LOGLEVEL
;

CREATE TABLE PDI4.R_LOGLEVEL
(
  ID_LOGLEVEL INTEGER
, CODE VARCHAR2(255)
, DESCRIPTION VARCHAR2(255)
, PRIMARY KEY (ID_LOGLEVEL)
)
;

INSERT INTO PDI4.R_LOGLEVEL(ID_LOGLEVEL, CODE, DESCRIPTION) VALUES (1,'Error','Error');

INSERT INTO PDI4.R_LOGLEVEL(ID_LOGLEVEL, CODE, DESCRIPTION) VALUES (2,'Minimal','Minimal');

INSERT INTO PDI4.R_LOGLEVEL(ID_LOGLEVEL, CODE, DESCRIPTION) VALUES (3,'Basic','Basic');

INSERT INTO PDI4.R_LOGLEVEL(ID_LOGLEVEL, CODE, DESCRIPTION) VALUES (4,'Detailed','Detailed');

INSERT INTO PDI4.R_LOGLEVEL(ID_LOGLEVEL, CODE, DESCRIPTION) VALUES (5,'Debug','Debug');

INSERT INTO PDI4.R_LOGLEVEL(ID_LOGLEVEL, CODE, DESCRIPTION) VALUES (6,'Rowlevel','Row Level (very detailed)');
