DROP TABLE PDI4.R_NOTE
;


CREATE TABLE PDI4.R_NOTE
(
  ID_NOTE INTEGER
, VALUE_STR CLOB
, GUI_LOCATION_X INTEGER
, GUI_LOCATION_Y INTEGER
, GUI_LOCATION_WIDTH INTEGER
, GUI_LOCATION_HEIGHT INTEGER
, FONT_NAME CLOB
, FONT_SIZE INTEGER
, FONT_BOLD CHAR(1)
, FONT_ITALIC CHAR(1)
, FONT_COLOR_RED INTEGER
, FONT_COLOR_GREEN INTEGER
, FONT_COLOR_BLUE INTEGER
, FONT_BACK_GROUND_COLOR_RED INTEGER
, FONT_BACK_GROUND_COLOR_GREEN INTEGER
, FONT_BACK_GROUND_COLOR_BLUE INTEGER
, FONT_BORDER_COLOR_RED INTEGER
, FONT_BORDER_COLOR_GREEN INTEGER
, FONT_BORDER_COLOR_BLUE INTEGER
, DRAW_SHADOW CHAR(1)
, PRIMARY KEY (ID_NOTE)
)
;