DROP TABLE PDI4.R_REPOSITORY_LOG
;

CREATE TABLE PDI4.R_REPOSITORY_LOG
(
  ID_REPOSITORY_LOG INTEGER
, REP_VERSION VARCHAR2(255)
, LOG_DATE DATE
, LOG_USER VARCHAR2(255)
, OPERATION_DESC CLOB
, PRIMARY KEY (ID_REPOSITORY_LOG)
)
;