DROP TABLE PDI4.R_STEP_DATABASE
;

CREATE TABLE PDI4.R_STEP_DATABASE
(
  ID_TRANSFORMATION INTEGER
, ID_STEP INTEGER
, ID_DATABASE INTEGER
)
;

CREATE INDEX IDX_4_RSD1 ON PDI4.R_STEP_DATABASE(ID_TRANSFORMATION)
;

CREATE INDEX IDX_4_RSD2 ON PDI4.R_STEP_DATABASE(ID_DATABASE)
;