DROP TABLE PDI4.R_TRANS_HOP
;

CREATE TABLE PDI4.R_TRANS_HOP
(
  ID_TRANS_HOP INTEGER
, ID_TRANSFORMATION INTEGER
, ID_STEP_FROM INTEGER
, ID_STEP_TO INTEGER
, ENABLED CHAR(1)
, PRIMARY KEY (ID_TRANS_HOP)
)
;