--needs to be run by privileged user 
--prompts for password to be entered

DROP USER PDI CASCADE;

CREATE USER PDI
  IDENTIFIED BY &pwd
  DEFAULT TABLESPACE ERX_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE SERVICE_ACCOUNT_PROFILE
  ACCOUNT UNLOCK;
  GRANT CONNECT TO PDI;
  GRANT RESOURCE TO PDI;
  ALTER USER PDI DEFAULT ROLE ALL;
  GRANT UNLIMITED TABLESPACE TO PDI;
