DROP TABLE PDI.R_DATABASE
;

CREATE TABLE PDI.R_DATABASE
(
  ID_DATABASE INTEGER
, NAME VARCHAR2(255)
, ID_DATABASE_TYPE INTEGER
, ID_DATABASE_CONTYPE INTEGER
, HOST_NAME VARCHAR2(255)
, DATABASE_NAME CLOB
, PORT INTEGER
, USERNAME VARCHAR2(255)
, PASSWORD VARCHAR2(255)
, SERVERNAME VARCHAR2(255)
, DATA_TBS VARCHAR2(255)
, INDEX_TBS VARCHAR2(255)
, PRIMARY KEY (ID_DATABASE)
)
;