DROP TABLE PDI.R_JOB_ATTRIBUTE
;

CREATE TABLE PDI.R_JOB_ATTRIBUTE
(
  ID_JOB_ATTRIBUTE INTEGER
, ID_JOB INTEGER
, NR INTEGER
, CODE VARCHAR2(255)
, VALUE_NUM INTEGER
, VALUE_STR CLOB
, PRIMARY KEY (ID_JOB_ATTRIBUTE)
)
;

CREATE UNIQUE INDEX IDX_JATT ON PDI.R_JOB_ATTRIBUTE(ID_JOB, CODE, NR)
;