DROP TABLE PDI.R_JOBENTRY_ATTRIBUTE
;

CREATE TABLE PDI.R_JOBENTRY_ATTRIBUTE
(
  ID_JOBENTRY_ATTRIBUTE INTEGER
, ID_JOB INTEGER
, ID_JOBENTRY INTEGER
, NR INTEGER
, CODE VARCHAR2(255)
, VALUE_NUM NUMBER(13, 2)
, VALUE_STR CLOB
, PRIMARY KEY (ID_JOBENTRY_ATTRIBUTE)
)
;

CREATE UNIQUE INDEX IDX_RJEA ON PDI.R_JOBENTRY_ATTRIBUTE(ID_JOBENTRY_ATTRIBUTE, CODE, NR)
;