DROP TABLE PDI.R_JOB_HOP
;


CREATE TABLE PDI.R_JOB_HOP
(
  ID_JOB_HOP INTEGER
, ID_JOB INTEGER
, ID_JOBENTRY_COPY_FROM INTEGER
, ID_JOBENTRY_COPY_TO INTEGER
, ENABLED CHAR(1)
, EVALUATION CHAR(1)
, UNCONDITIONAL CHAR(1)
, PRIMARY KEY (ID_JOB_HOP)
)
;