DROP TABLE PDI.R_LOG
;


CREATE TABLE PDI.R_LOG
(
  ID_LOG INTEGER
, NAME VARCHAR2(255)
, ID_LOGLEVEL INTEGER
, LOGTYPE VARCHAR2(255)
, FILENAME VARCHAR2(255)
, FILEEXTENTION VARCHAR2(255)
, ADD_DATE CHAR(1)
, ADD_TIME CHAR(1)
, ID_DATABASE_LOG INTEGER
, TABLE_NAME_LOG VARCHAR2(255)
, PRIMARY KEY (ID_LOG)
)
;