DROP TABLE PDI.R_PARTITION_SCHEMA
;

CREATE TABLE PDI.R_PARTITION_SCHEMA
(
  ID_PARTITION_SCHEMA INTEGER
, NAME VARCHAR2(255)
, DYNAMIC_DEFINITION CHAR(1)
, PARTITIONS_PER_SLAVE VARCHAR2(255)
, PRIMARY KEY (ID_PARTITION_SCHEMA)
)
;