DROP TABLE PDI.R_TRANS_PARTITION_SCHEMA
;

CREATE TABLE PDI.R_TRANS_PARTITION_SCHEMA
(
  ID_TRANS_PARTITION_SCHEMA INTEGER
, ID_TRANSFORMATION INTEGER
, ID_PARTITION_SCHEMA INTEGER
, PRIMARY KEY (ID_TRANS_PARTITION_SCHEMA)
)
;