DROP TABLE PDI.R_VERSION
;

CREATE TABLE PDI.R_VERSION
(
  ID_VERSION INTEGER
, MAJOR_VERSION INTEGER
, MINOR_VERSION INTEGER
, UPGRADE_DATE DATE
, IS_UPGRADE CHAR(1)
, PRIMARY KEY (ID_VERSION)
)
;

INSERT INTO PDI.R_VERSION(ID_VERSION, MAJOR_VERSION, MINOR_VERSION, UPGRADE_DATE, IS_UPGRADE) VALUES (1,5,0,TO_DATE('2016/08/16 09:05:27', 'YYYY/MM/DD HH24:MI:SS'),'N');