package gov.va.med.pharmacy.wsclients.mvi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-01T15:21:23.799-04:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://vaww.oed.oit.va.gov", name = "VAIdMPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VAIdMPort {

    @WebMethod(operationName = "PRPA_IN201305UV02")
    @WebResult(name = "PRPA_IN201306UV02", targetNamespace = "http://vaww.oed.oit.va.gov", partName = "returnXML")
    public PRPAIN201306UV02 prpaIN201305UV02(
        @WebParam(partName = "inboundXML", name = "PRPA_IN201305UV02", targetNamespace = "http://vaww.oed.oit.va.gov")
        PRPAIN201305UV02 inboundXML
    );
}
