DROP TABLE PDI.R_CLUSTER
;

CREATE TABLE PDI.R_CLUSTER
(
  ID_CLUSTER INTEGER
, NAME VARCHAR2(255)
, BASE_PORT VARCHAR2(255)
, SOCKETS_BUFFER_SIZE VARCHAR2(255)
, SOCKETS_FLUSH_INTERVAL VARCHAR2(255)
, SOCKETS_COMPRESSED CHAR(1)
, DYNAMIC_CLUSTER CHAR(1)
, PRIMARY KEY (ID_CLUSTER)
)
;
