DROP TABLE PDI.R_DIRECTORY
;


CREATE TABLE PDI.R_DIRECTORY
(
  ID_DIRECTORY INTEGER
, ID_DIRECTORY_PARENT INTEGER
, DIRECTORY_NAME VARCHAR2(255)
, PRIMARY KEY (ID_DIRECTORY)
)
;

CREATE UNIQUE INDEX IDX_RDIR ON PDI.R_DIRECTORY(ID_DIRECTORY_PARENT, DIRECTORY_NAME)
;