DROP TABLE PDI.R_ELEMENT_ATTRIBUTE
;

CREATE TABLE PDI.R_ELEMENT_ATTRIBUTE
(
  ID_ELEMENT_ATTRIBUTE INTEGER
, ID_ELEMENT INTEGER
, ID_ELEMENT_ATTRIBUTE_PARENT INTEGER
, ATTR_KEY VARCHAR2(255)
, ATTR_VALUE CLOB
, PRIMARY KEY (ID_ELEMENT_ATTRIBUTE)
)
;