DROP TABLE PDI.R_JOBENTRY_DATABASE
;

CREATE TABLE PDI.R_JOBENTRY_DATABASE
(
  ID_JOB INTEGER
, ID_JOBENTRY INTEGER
, ID_DATABASE INTEGER
)
;

CREATE INDEX IDX_RJD1 ON PDI.R_JOBENTRY_DATABASE(ID_JOB)
;

CREATE INDEX IDX_RJD2 ON PDI.R_JOBENTRY_DATABASE(ID_DATABASE)
;