DROP TABLE PDI.R_STEP_DATABASE
;

CREATE TABLE PDI.R_STEP_DATABASE
(
  ID_TRANSFORMATION INTEGER
, ID_STEP INTEGER
, ID_DATABASE INTEGER
)
;

CREATE INDEX IDX_RSD1 ON PDI.R_STEP_DATABASE(ID_TRANSFORMATION)
;

CREATE INDEX IDX_RSD2 ON PDI.R_STEP_DATABASE(ID_DATABASE)
;