CREATE OR REPLACE TRIGGER ERX.APP_CONFIGURATION_TRG 
    BEFORE INSERT OR UPDATE ON ERX.APP_CONFIGURATION 
    FOR EACH ROW 
BEGIN 
IF UPDATING THEN
  :NEW.UPDATED_DATE := SYSDATE;
ELSE
  :NEW.CREATED_DATE := SYSDATE;
END IF;
END; 
/


