DROP USER ERX_UPDATE_USER CASCADE;

CREATE USER ERX_UPDATE_USER
  IDENTIFIED BY &pwd
  DEFAULT TABLESPACE ERX_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE SERVICE_ACCOUNT_PROFILE
  ACCOUNT UNLOCK;
  -- 3 Roles for ERX_UPDATE_USER 
  GRANT CONNECT TO ERX_UPDATE_USER;
  GRANT ERX_UPDATE_ROLE TO ERX_UPDATE_USER;
  ALTER USER ERX_UPDATE_USER DEFAULT ROLE ALL;
  -- 1 System Privilege for ERX_UPDATE_USER 
  GRANT UNLIMITED TABLESPACE TO ERX_UPDATE_USER;