CREATE OR REPLACE TRIGGER ERX.MONITORING_TRG
    BEFORE INSERT OR UPDATE ON ERX.MONITORING
    FOR EACH ROW
BEGIN
  :NEW.CREATED_DATE := SYSDATE;
  IF :NEW.MONITORING_ID IS NULL THEN
  :NEW.MONITORING_ID := MONITORING_ID_SEQ.NEXTVAL;
  END IF;
END;