DROP TABLE ERX.NCPDP_CODE CASCADE CONSTRAINTS ;

CREATE TABLE ERX.NCPDP_CODE
  (
    NCIT_SUBSET_CODE     	VARCHAR2(7),
    NCPDP_SUBSET_PREF_TERM 	VARCHAR2(100),
    NCIT_CODE  	  		   	VARCHAR2(7),
    NCPDP_PREF_TERM 		VARCHAR2(100),
    NCPDP_SYNONYM      		VARCHAR2(100),
  	NCIT_PREF_TERM       	VARCHAR2(100),
  	NCIT_DEFINITION     	VARCHAR2(2000)
  )
  LOGGING ;