ALTER TABLE ERX.PHARMACY ADD CONSTRAINT PHARMACY_PK PRIMARY KEY ( PHARMACY_ID ) USING INDEX ERX.PHARMACY_PK ;

ALTER TABLE ERX.PHARMACY ADD CONSTRAINT NCPDP_ID_UK UNIQUE ( NCPDP_ID ) USING INDEX ERX.NCPDP_ID_UK ;

ALTER TABLE ERX.PHARMACY ADD CONSTRAINT NPI_UK UNIQUE ( NPI ) USING INDEX ERX.NPI_UK ;

ALTER TABLE ERX.PHARMACY ADD CONSTRAINT DIVISION_NAME_UK UNIQUE ( DIVISION_NAME ) USING INDEX ERX.DIVISION_NAME_UK ;

ALTER TABLE ERX.PHARMACY ADD CONSTRAINT VA_STATION_ID_UK UNIQUE ( VA_STATION_ID ) USING INDEX ERX.VA_STATION_ID_UK ;

