--Drops, creates and loads erx.loinc_code table

DROP TABLE "ERX"."LOINC_CODE";
/

CREATE TABLE "ERX"."LOINC_CODE" 
   (	"LOINC_NUM" VARCHAR2(26 BYTE), 
	"COMPONENT" VARCHAR2(500 BYTE), 
	"PROPERTY" VARCHAR2(50 BYTE), 
	"TIME_ASPCT" VARCHAR2(26 BYTE), 
	"SYSTEM" VARCHAR2(400 BYTE), 
	"SCALE_TYP" VARCHAR2(26 BYTE), 
	"METHOD_TYP" VARCHAR2(100 BYTE), 
	"CLASS" VARCHAR2(26 BYTE), 
	"VERSIONLASTCHANGED" VARCHAR2(50 BYTE), 
	"CHNG_TYPE" VARCHAR2(26 BYTE), 
	"DEFINITIONDESCRIPTION" CLOB, 
	"STATUS" VARCHAR2(100 BYTE), 
	"CONSUMER_NAME" VARCHAR2(26 BYTE), 
	"CLASSTYPE" VARCHAR2(50 BYTE), 
	"FORMULA" VARCHAR2(500 BYTE), 
	"SPECIES" VARCHAR2(26 BYTE), 
	"EXMPL_ANSWERS" CLOB, 
	"SURVEY_QUEST_TEXT" VARCHAR2(1000 BYTE), 
	"SURVEY_QUEST_SRC" VARCHAR2(50 BYTE), 
	"UNITSREQUIRED" VARCHAR2(26 BYTE), 
	"SUBMITTED_UNITS" VARCHAR2(150 BYTE), 
	"RELATEDNAMES2" VARCHAR2(2000 BYTE), 
	"SHORTNAME" VARCHAR2(100 BYTE), 
	"ORDER_OBS" VARCHAR2(26 BYTE), 
	"CDISC_COMMON_TESTS" VARCHAR2(26 BYTE), 
	"HL7_FIELD_SUBFIELD_ID" VARCHAR2(26 BYTE), 
	"EXTERNAL_COPYRIGHT_NOTICE" VARCHAR2(3000 BYTE), 
	"EXAMPLE_UNITS" VARCHAR2(50 BYTE), 
	"LONG_COMMON_NAME" VARCHAR2(400 BYTE), 
	"UNITSANDRANGE" VARCHAR2(30 BYTE), 
	"EXAMPLE_UCUM_UNITS" VARCHAR2(100 BYTE), 
	"EXAMPLE_SI_UCUM_UNITS" VARCHAR2(26 BYTE), 
	"STATUS_REASON" VARCHAR2(26 BYTE), 
	"STATUS_TEXT" VARCHAR2(1000 BYTE), 
	"CHANGE_REASON_PUBLIC" VARCHAR2(1500 BYTE), 
	"COMMON_TEST_RANK" VARCHAR2(50 BYTE), 
	"COMMON_ORDER_RANK" VARCHAR2(50 BYTE), 
	"COMMON_SI_TEST_RANK" VARCHAR2(50 BYTE), 
	"HL7_ATTACHMENT_STRUCTURE" VARCHAR2(26 BYTE), 
	"EXTERNAL_COPYRIGHT_LINK" VARCHAR2(26 BYTE), 
	"PANELTYPE" VARCHAR2(26 BYTE), 
	"ASKATORDERENTRY" VARCHAR2(26 BYTE), 
	"ASSOCIATEDOBSERVATIONS" VARCHAR2(100 BYTE), 
	"VERSIONFIRSTRELEASED" VARCHAR2(26 BYTE), 
	"VALIDHL7ATTACHMENTREQUEST" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERX_DATA" 
 LOB ("DEFINITIONDESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "ERX_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EXMPL_ANSWERS") STORE AS SECUREFILE (
  TABLESPACE "ERX_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

/


COMMIT;
/

GRANT SELECT ON ERX.LOINC_CODE to ERX_READ_ROLE;
GRANT SELECT ON ERX.LOINC_CODE to ERX_UPDATE_ROLE;
GRANT SELECT ON ERX.LOINC_CODE to ERX_READ_DEIDENT_ROLE;
/

create public synonym loinc_code for erx.loinc_code;
/
-- Import Data into table LOINC_CODE. Task successful.
