--Task EPRESCRIB-1977
--Modifing OUTBOUND_NCPDP_MSG and INBOUND_NCPDP_MSG table triggers to only
--set the CREATED_DATE if it is null on insert to aid in data migration activities

CREATE OR REPLACE TRIGGER ERX.OB_NCPDP_MSG_TRG 
    BEFORE INSERT OR UPDATE ON ERX.OUTBOUND_NCPDP_MSG 
    FOR EACH ROW 
BEGIN 
IF UPDATING THEN
  :NEW.UPDATED_DATE := SYSDATE;
ELSE
	IF :NEW.CREATED_DATE IS NULL THEN
		:NEW.CREATED_DATE := SYSDATE;
	END IF;
	IF :NEW.OUTBOUND_NCPDP_MSG_ID IS NULL THEN
		:NEW.OUTBOUND_NCPDP_MSG_ID := OB_NCPDP_MSG_ID_SEQ.NEXTVAL;
	END IF;
END IF;
END; 
/


CREATE OR REPLACE TRIGGER ERX.IB_NCPDP_MSG_TRG
    BEFORE INSERT OR UPDATE ON ERX.INBOUND_NCPDP_MSG
    FOR EACH ROW
DECLARE
    xml_status NUMBER;
BEGIN
IF UPDATING THEN
  :NEW.UPDATED_DATE := SYSDATE; 
ELSE
  	IF :NEW.CREATED_DATE IS NULL THEN
		:NEW.CREATED_DATE := SYSDATE;
	END IF;
   IF :NEW.INBOUND_NCPDP_MSG_ID IS NULL THEN
    :NEW.INBOUND_NCPDP_MSG_ID := IB_NCPDP_MSG_ID_SEQ.NEXTVAL;
   END IF; 
END IF;
END;
/