--needs to be run by privileged user 
--prompts for password to be entered

DROP USER ERX CASCADE;

CREATE USER ERX
  IDENTIFIED BY &pwd
  DEFAULT TABLESPACE ERX_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE SERVICE_ACCOUNT_PROFILE
  ACCOUNT UNLOCK;
  GRANT CONNECT TO ERX;
  GRANT RESOURCE TO ERX;
  ALTER USER ERX DEFAULT ROLE ALL;
  GRANT UNLIMITED TABLESPACE TO ERX;
