CREATE OR REPLACE TRIGGER ERX.ERX_STATUS_TRG 
    BEFORE INSERT OR UPDATE ON ERX.ERX_STATUS 
    FOR EACH ROW 
BEGIN 
IF UPDATING THEN
  :NEW.UPDATED_DATE := SYSDATE;
ELSE
  :NEW.CREATED_DATE := SYSDATE;
END IF;
END; 
/


