DROP TABLE ERX.VA_USER CASCADE CONSTRAINTS ;

CREATE TABLE ERX.VA_USER
  (
    USERS_ID     NUMBER NOT NULL ,
    VA_USERID    VARCHAR2 (20) NOT NULL ,
    FIRST_NAME  VARCHAR2(50) ,
    LAST_NAME VARCHAR2(50) ,
    IS_PHARM_MGR      VARCHAR2(1 BYTE)    DEFAULT 'N' NOT NULL, 
  	IS_PBM_ADMN       VARCHAR2(1 BYTE)    DEFAULT 'N' NOT NULL,
  	IS_PHARM_TECH     VARCHAR2(1 BYTE)    DEFAULT 'N' NOT NULL,
  	IS_SYSTEM_ADMN    VARCHAR2(1 BYTE)    DEFAULT 'N' NOT NULL,
    UPDATED_DATE DATE ,
    CREATED_DATE DATE ,
    CREATED_BY VARCHAR2(20 BYTE), 
	UPDATED_BY VARCHAR2(20 BYTE) 
  )
  LOGGING ;