//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnswerChoiceForPARequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnswerChoiceForPARequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChoiceID" type="{}an1..35"/>
 *         &lt;element name="AdditionalFreeText" type="{}an1..2000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnswerChoiceForPARequest", propOrder = {
    "choiceID",
    "additionalFreeText"
})
public class AnswerChoiceForPARequest {

    @XmlElement(name = "ChoiceID", required = true)
    protected String choiceID;
    @XmlElement(name = "AdditionalFreeText")
    protected String additionalFreeText;

    /**
     * Gets the value of the choiceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChoiceID() {
        return choiceID;
    }

    /**
     * Sets the value of the choiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChoiceID(String value) {
        this.choiceID = value;
    }

    /**
     * Gets the value of the additionalFreeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalFreeText() {
        return additionalFreeText;
    }

    /**
     * Sets the value of the additionalFreeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalFreeText(String value) {
        this.additionalFreeText = value;
    }

}
