//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Attachment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Attachment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AttachmentSource" type="{}an"/>
 *         &lt;element name="AttachmentData" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;group ref="{}ClinicalInformation"/>
 *         &lt;element name="MIMEType" type="{}MIMEType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Attachment", propOrder = {
    "attachmentSource",
    "attachmentData",
    "cda",
    "ccr",
    "mimeType"
})
public class Attachment {

    @XmlElement(name = "AttachmentSource", required = true)
    protected String attachmentSource;
    @XmlElement(name = "AttachmentData", required = true)
    protected byte[] attachmentData;
    @XmlElement(name = "CDA")
    protected CDATemplates cda;
    @XmlElement(name = "CCR")
    protected CCRVersion ccr;
    @XmlElement(name = "MIMEType", required = true)
    @XmlSchemaType(name = "string")
    protected MIMEType mimeType;

    /**
     * Gets the value of the attachmentSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachmentSource() {
        return attachmentSource;
    }

    /**
     * Sets the value of the attachmentSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachmentSource(String value) {
        this.attachmentSource = value;
    }

    /**
     * Gets the value of the attachmentData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getAttachmentData() {
        return attachmentData;
    }

    /**
     * Sets the value of the attachmentData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setAttachmentData(byte[] value) {
        this.attachmentData = value;
    }

    /**
     * Gets the value of the cda property.
     * 
     * @return
     *     possible object is
     *     {@link CDATemplates }
     *     
     */
    public CDATemplates getCDA() {
        return cda;
    }

    /**
     * Sets the value of the cda property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDATemplates }
     *     
     */
    public void setCDA(CDATemplates value) {
        this.cda = value;
    }

    /**
     * Gets the value of the ccr property.
     * 
     * @return
     *     possible object is
     *     {@link CCRVersion }
     *     
     */
    public CCRVersion getCCR() {
        return ccr;
    }

    /**
     * Sets the value of the ccr property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCRVersion }
     *     
     */
    public void setCCR(CCRVersion value) {
        this.ccr = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link MIMEType }
     *     
     */
    public MIMEType getMIMEType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIMEType }
     *     
     */
    public void setMIMEType(MIMEType value) {
        this.mimeType = value;
    }

}
