//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFCounsel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFCounsel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Counsel" type="{}BooleanCode" minOccurs="0"/>
 *         &lt;element name="CounselNotes" type="{}an"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFCounsel", propOrder = {
    "counsel",
    "counselNotes"
})
public class CFCounsel {

    @XmlElement(name = "Counsel")
    @XmlSchemaType(name = "string")
    protected BooleanCode counsel;
    @XmlElement(name = "CounselNotes", required = true)
    protected String counselNotes;

    /**
     * Gets the value of the counsel property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanCode }
     *     
     */
    public BooleanCode getCounsel() {
        return counsel;
    }

    /**
     * Sets the value of the counsel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanCode }
     *     
     */
    public void setCounsel(BooleanCode value) {
        this.counsel = value;
    }

    /**
     * Gets the value of the counselNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounselNotes() {
        return counselNotes;
    }

    /**
     * Sets the value of the counselNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounselNotes(String value) {
        this.counselNotes = value;
    }

}
