//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFDrugImprint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFDrugImprint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{}an"/>
 *         &lt;element name="Markings" type="{}an"/>
 *         &lt;element name="DrugShape" type="{}an"/>
 *         &lt;element name="Flavor" type="{}an"/>
 *         &lt;element name="Imprint1" type="{}an"/>
 *         &lt;element name="Imprint2" type="{}an"/>
 *         &lt;element name="Color" type="{}an"/>
 *         &lt;element name="Coating" type="{}an"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFDrugImprint", propOrder = {
    "description",
    "markings",
    "drugShape",
    "flavor",
    "imprint1",
    "imprint2",
    "color",
    "coating"
})
public class CFDrugImprint {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Markings", required = true)
    protected String markings;
    @XmlElement(name = "DrugShape", required = true)
    protected String drugShape;
    @XmlElement(name = "Flavor", required = true)
    protected String flavor;
    @XmlElement(name = "Imprint1", required = true)
    protected String imprint1;
    @XmlElement(name = "Imprint2", required = true)
    protected String imprint2;
    @XmlElement(name = "Color", required = true)
    protected String color;
    @XmlElement(name = "Coating", required = true)
    protected String coating;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the markings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkings() {
        return markings;
    }

    /**
     * Sets the value of the markings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkings(String value) {
        this.markings = value;
    }

    /**
     * Gets the value of the drugShape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugShape() {
        return drugShape;
    }

    /**
     * Sets the value of the drugShape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugShape(String value) {
        this.drugShape = value;
    }

    /**
     * Gets the value of the flavor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlavor() {
        return flavor;
    }

    /**
     * Sets the value of the flavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlavor(String value) {
        this.flavor = value;
    }

    /**
     * Gets the value of the imprint1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprint1() {
        return imprint1;
    }

    /**
     * Sets the value of the imprint1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprint1(String value) {
        this.imprint1 = value;
    }

    /**
     * Gets the value of the imprint2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprint2() {
        return imprint2;
    }

    /**
     * Sets the value of the imprint2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprint2(String value) {
        this.imprint2 = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the coating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoating() {
        return coating;
    }

    /**
     * Sets the value of the coating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoating(String value) {
        this.coating = value;
    }

}
