//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFGenericSubstitutedForBrand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFGenericSubstitutedForBrand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubstitutedBrandDrug" type="{}an"/>
 *         &lt;element name="SubstitutionMessage" type="{}an"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFGenericSubstitutedForBrand", propOrder = {
    "substitutedBrandDrug",
    "substitutionMessage"
})
public class CFGenericSubstitutedForBrand {

    @XmlElement(name = "SubstitutedBrandDrug", required = true)
    protected String substitutedBrandDrug;
    @XmlElement(name = "SubstitutionMessage", required = true)
    protected String substitutionMessage;

    /**
     * Gets the value of the substitutedBrandDrug property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstitutedBrandDrug() {
        return substitutedBrandDrug;
    }

    /**
     * Sets the value of the substitutedBrandDrug property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstitutedBrandDrug(String value) {
        this.substitutedBrandDrug = value;
    }

    /**
     * Gets the value of the substitutionMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstitutionMessage() {
        return substitutionMessage;
    }

    /**
     * Sets the value of the substitutionMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstitutionMessage(String value) {
        this.substitutionMessage = value;
    }

}
