//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFRxOrderCancelDeniedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFRxOrderCancelDeniedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{}SpecializedDeniedAbstractType">
 *       &lt;sequence>
 *         &lt;element name="ReasonCode" type="{}ReasonCode16" maxOccurs="10"/>
 *         &lt;element name="ReferenceNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="DenialReason" type="{}an" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFRxOrderCancelDeniedType")
public class CFRxOrderCancelDeniedType
    extends SpecializedDeniedAbstractType
{


}
