//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodedReferenceAnswerChoiceDateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodedReferenceAnswerChoiceDateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Date" type="{}DateType"/>
 *         &lt;element name="SeeTransactionLevelAttachmentControlNumber" type="{}an"/>
 *         &lt;element name="AnswerValue" type="{}an1..2000"/>
 *         &lt;element name="Attachment" type="{}AttachmentWithControlNumber"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodedReferenceAnswerChoiceDateType", propOrder = {
    "date",
    "seeTransactionLevelAttachmentControlNumber",
    "answerValue",
    "attachment"
})
public class CodedReferenceAnswerChoiceDateType {

    @XmlElement(name = "Date")
    protected DateType date;
    @XmlElement(name = "SeeTransactionLevelAttachmentControlNumber")
    protected String seeTransactionLevelAttachmentControlNumber;
    @XmlElement(name = "AnswerValue")
    protected String answerValue;
    @XmlElement(name = "Attachment")
    protected AttachmentWithControlNumber attachment;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDate(DateType value) {
        this.date = value;
    }

    /**
     * Gets the value of the seeTransactionLevelAttachmentControlNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeeTransactionLevelAttachmentControlNumber() {
        return seeTransactionLevelAttachmentControlNumber;
    }

    /**
     * Sets the value of the seeTransactionLevelAttachmentControlNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeeTransactionLevelAttachmentControlNumber(String value) {
        this.seeTransactionLevelAttachmentControlNumber = value;
    }

    /**
     * Gets the value of the answerValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswerValue() {
        return answerValue;
    }

    /**
     * Sets the value of the answerValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswerValue(String value) {
        this.answerValue = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentWithControlNumber }
     *     
     */
    public AttachmentWithControlNumber getAttachment() {
        return attachment;
    }

    /**
     * Sets the value of the attachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentWithControlNumber }
     *     
     */
    public void setAttachment(AttachmentWithControlNumber value) {
        this.attachment = value;
    }

}
