//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommunicationNumbersTypeRestricted complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommunicationNumbersTypeRestricted">
 *   &lt;complexContent>
 *     &lt;restriction base="{}CommunicationNumbersType">
 *       &lt;sequence>
 *         &lt;element name="PrimaryTelephone" type="{}PhoneType"/>
 *         &lt;element name="Beeper" type="{}PhoneType" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ElectronicMail" type="{}MailAddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Fax" type="{}PhoneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HomeTelephone" type="{}PhoneType" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="WorkTelephone" type="{}PhoneType" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="OtherTelephone" type="{}PhoneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DirectAddress" type="{}an1..254" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommunicationNumbersTypeRestricted")
public class CommunicationNumbersTypeRestricted
    extends CommunicationNumbersType
{


}
