//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompletedAnswerChoiceForSelectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompletedAnswerChoiceForSelectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PrescriberProvidedAnswer" type="{}AnswerChoiceForPARequest"/>
 *         &lt;element name="CodedReferenceAnswer" type="{}CodedReferenceAnswerChoiceSelectType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompletedAnswerChoiceForSelectType", propOrder = {
    "prescriberProvidedAnswer",
    "codedReferenceAnswer"
})
public class CompletedAnswerChoiceForSelectType {

    @XmlElement(name = "PrescriberProvidedAnswer")
    protected AnswerChoiceForPARequest prescriberProvidedAnswer;
    @XmlElement(name = "CodedReferenceAnswer")
    protected CodedReferenceAnswerChoiceSelectType codedReferenceAnswer;

    /**
     * Gets the value of the prescriberProvidedAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link AnswerChoiceForPARequest }
     *     
     */
    public AnswerChoiceForPARequest getPrescriberProvidedAnswer() {
        return prescriberProvidedAnswer;
    }

    /**
     * Sets the value of the prescriberProvidedAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnswerChoiceForPARequest }
     *     
     */
    public void setPrescriberProvidedAnswer(AnswerChoiceForPARequest value) {
        this.prescriberProvidedAnswer = value;
    }

    /**
     * Gets the value of the codedReferenceAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link CodedReferenceAnswerChoiceSelectType }
     *     
     */
    public CodedReferenceAnswerChoiceSelectType getCodedReferenceAnswer() {
        return codedReferenceAnswer;
    }

    /**
     * Sets the value of the codedReferenceAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedReferenceAnswerChoiceSelectType }
     *     
     */
    public void setCodedReferenceAnswer(CodedReferenceAnswerChoiceSelectType value) {
        this.codedReferenceAnswer = value;
    }

}
