//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Drug Composition Structure
 * 
 * <p>Java class for CompoundIngredientLotNotUsedNoDUE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompoundIngredientLotNotUsedNoDUE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompoundIngredient" type="{}IngredientLotNotUsedForPAandREM" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{}CompoundQuantity"/>
 *         &lt;element name="DrugUseEvaluation" type="{}DrugUseEvaluation" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompoundIngredientLotNotUsedNoDUE", propOrder = {
    "compoundIngredient",
    "quantity"
})
public class CompoundIngredientLotNotUsedNoDUE {

    @XmlElement(name = "CompoundIngredient")
    protected IngredientLotNotUsedForPAandREM compoundIngredient;
    @XmlElement(name = "Quantity", required = true)
    protected CompoundQuantity quantity;

    /**
     * Gets the value of the compoundIngredient property.
     * 
     * @return
     *     possible object is
     *     {@link IngredientLotNotUsedForPAandREM }
     *     
     */
    public IngredientLotNotUsedForPAandREM getCompoundIngredient() {
        return compoundIngredient;
    }

    /**
     * Sets the value of the compoundIngredient property.
     * 
     * @param value
     *     allowed object is
     *     {@link IngredientLotNotUsedForPAandREM }
     *     
     */
    public void setCompoundIngredient(IngredientLotNotUsedForPAandREM value) {
        this.compoundIngredient = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link CompoundQuantity }
     *     
     */
    public CompoundQuantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompoundQuantity }
     *     
     */
    public void setQuantity(CompoundQuantity value) {
        this.quantity = value;
    }

}
