//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryLocation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeliveryLocation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HOME"/>
 *     &lt;enumeration value="FACILITY"/>
 *     &lt;enumeration value="CONTACT PATIENT FOR DELIVERY"/>
 *     &lt;enumeration value="AGENCY OF SERVICE"/>
 *     &lt;enumeration value="PROVIDER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeliveryLocation")
@XmlEnum
public enum DeliveryLocation {


    /**
     * Use patient address.
     * 
     */
    HOME("HOME"),

    /**
     * Use facility address.
     * 
     */
    FACILITY("FACILITY"),

    /**
     * Contact information is contained in patient elements.
     * 
     */
    @XmlEnumValue("CONTACT PATIENT FOR DELIVERY")
    CONTACT_PATIENT_FOR_DELIVERY("CONTACT PATIENT FOR DELIVERY"),

    /**
     * Use agency of service address.
     * 
     */
    @XmlEnumValue("AGENCY OF SERVICE")
    AGENCY_OF_SERVICE("AGENCY OF SERVICE"),

    /**
     * Use provider address.
     * 
     */
    PROVIDER("PROVIDER");
    private final String deliveryLocationValue;

    DeliveryLocation(String v) {
    	deliveryLocationValue = v;
    }

    public String value() {
        return deliveryLocationValue;
    }

    public static DeliveryLocation fromValue(String v) {
        for (DeliveryLocation c: DeliveryLocation.values()) {
            if (c.deliveryLocationValue.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
