//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryRequest.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeliveryRequest">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NO DELIVERY"/>
 *     &lt;enumeration value="FIRST FILL DELIVERY"/>
 *     &lt;enumeration value="ALL FILLS DELIVERY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeliveryRequest")
@XmlEnum
public enum DeliveryRequest {


    /**
     * No delivery required.
     * 
     */
    @XmlEnumValue("NO DELIVERY")
    NO_DELIVERY("NO DELIVERY"),

    /**
     * Deliver only first fill of prescription.
     * 
     */
    @XmlEnumValue("FIRST FILL DELIVERY")
    FIRST_FILL_DELIVERY("FIRST FILL DELIVERY"),

    /**
     * Deliver all fills of prescription.
     * 
     */
    @XmlEnumValue("ALL FILLS DELIVERY")
    ALL_FILLS_DELIVERY("ALL FILLS DELIVERY");
    private final String deliveryRequestValue;

    DeliveryRequest(String v) {
    	deliveryRequestValue = v;
    }

    public String value() {
        return deliveryRequestValue;
    }

    public static DeliveryRequest fromValue(String v) {
        for (DeliveryRequest c: DeliveryRequest.values()) {
            if (c.deliveryRequestValue.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
