//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiagnosisRestricted complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiagnosisRestricted">
 *   &lt;complexContent>
 *     &lt;restriction base="{}Diagnosis">
 *       &lt;sequence>
 *         &lt;element name="ClinicalInformationQualifier" type="{}ClinicalInformationQualifier"/>
 *         &lt;element name="Primary" type="{}DiagnosisQualifiedCodeWithDescriptionRestricted"/>
 *         &lt;element name="Secondary" type="{}DiagnosisQualifiedCodeWithDescriptionRestricted" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiagnosisRestricted")
public class DiagnosisRestricted
    extends Diagnosis
{


}
