//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DoNotFill.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DoNotFill">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="Y"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="E"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DoNotFill")
@XmlEnum
public enum DoNotFill {


    /**
     * Yes - Used for medications ordered by a prescriber not requiring dispensing, but available for reference and drug-to-drug interaction checking.  
     * 
     */
    Y,

    /**
     * Hold - Indicates the prescriber’s authorization for the pharmacy to fill a prescription, but the prescriber recommends that the pharmacy wait for the patient to request it before filling it.
     * 
     */
    H,

    /**
     * Do Not Fill – Used for a cover prescription for a previously called in emergency oral prescription as necessary for controlled substances.
     * 
     */
    E;

    public String value() {
        return name();
    }

    public static DoNotFill fromValue(String v) {
        return valueOf(v);
    }

}
