//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * FacilityID is explicit ID structure to improve comprehension and validation of ID by using explicit tags for each ID type
 * 
 * <p>Java class for FacilityID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FacilityID">
 *   &lt;complexContent>
 *     &lt;restriction base="{}SuperSetID">
 *       &lt;sequence>
 *         &lt;element name="NCPDPID" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="StateLicenseNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="MedicareNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="MedicaidNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="UPIN" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="FacilityID" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="PayerID" type="{}an1..80" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ProcessorIdentificationNumber" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="IINNumber" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="MedicalRecordIdentificationNumberEHR" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="PatientAccountNumber" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="DEANumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="HIN" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="NAICCode" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="SocialSecurity" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="NPI" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="CertificateToPrescribe" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Data2000WaiverID" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="MutuallyDefined" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="REMSHealthcareSettingEnrollmentID" type="{}an1..35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacilityID")
public class FacilityID
    extends SuperSetID
{


}
