//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="To" type="{}QualifiedAddress"/>
 *         &lt;element name="From" type="{}QualifiedAddress"/>
 *         &lt;element name="MessageID" type="{}an1..35"/>
 *         &lt;element name="RelatesToMessageID" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="SentTime" type="{}UtcDateType"/>
 *         &lt;element name="Security" type="{}SecurityType" minOccurs="0"/>
 *         &lt;element name="SenderSoftware" type="{}SenderSoftwareType"/>
 *         &lt;element name="Mailbox" type="{}MailboxType" minOccurs="0"/>
 *         &lt;element name="TestMessage" type="{}n1..1" minOccurs="0"/>
 *         &lt;element name="RxReferenceNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="TertiaryIdentifier" type="{}an1..3" minOccurs="0"/>
 *         &lt;element name="PrescriberOrderNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="DigitalSignature" type="{}DigitalSignature" minOccurs="0"/>
 *         &lt;element name="PrescriberOrderGroup" type="{}OrderGroup" minOccurs="0"/>
 *         &lt;element name="RxReferenceOrderGroup" type="{}OrderGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderType", propOrder = {
    "to",
    "from",
    "messageID",
    "relatesToMessageID",
    "sentTime",
    "security",
    "senderSoftware",
    "mailbox",
    "testMessage",
    "rxReferenceNumber",
    "tertiaryIdentifier",
    "prescriberOrderNumber",
    "digitalSignature",
    "prescriberOrderGroup",
    "rxReferenceOrderGroup"
})
public class HeaderType {

    @XmlElement(name = "To", required = true)
    protected QualifiedAddress to;
    @XmlElement(name = "From", required = true)
    protected QualifiedAddress from;
    @XmlElement(name = "MessageID", required = true)
    protected String messageID;
    @XmlElement(name = "RelatesToMessageID")
    protected String relatesToMessageID;
    @XmlElement(name = "SentTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sentTime;
    @XmlElement(name = "Security")
    protected SecurityType security;
    @XmlElement(name = "SenderSoftware", required = true)
    protected SenderSoftwareType senderSoftware;
    @XmlElement(name = "Mailbox")
    protected MailboxType mailbox;
    @XmlElement(name = "TestMessage")
    protected String testMessage;
    @XmlElement(name = "RxReferenceNumber")
    protected String rxReferenceNumber;
    @XmlElement(name = "TertiaryIdentifier")
    protected String tertiaryIdentifier;
    @XmlElement(name = "PrescriberOrderNumber")
    protected String prescriberOrderNumber;
    @XmlElement(name = "DigitalSignature")
    protected DigitalSignature digitalSignature;
    @XmlElement(name = "PrescriberOrderGroup")
    protected OrderGroup prescriberOrderGroup;
    @XmlElement(name = "RxReferenceOrderGroup")
    protected OrderGroup rxReferenceOrderGroup;

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiedAddress }
     *     
     */
    public QualifiedAddress getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiedAddress }
     *     
     */
    public void setTo(QualifiedAddress value) {
        this.to = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiedAddress }
     *     
     */
    public QualifiedAddress getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiedAddress }
     *     
     */
    public void setFrom(QualifiedAddress value) {
        this.from = value;
    }

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the relatesToMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatesToMessageID() {
        return relatesToMessageID;
    }

    /**
     * Sets the value of the relatesToMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatesToMessageID(String value) {
        this.relatesToMessageID = value;
    }

    /**
     * Gets the value of the sentTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSentTime() {
        return sentTime;
    }

    /**
     * Sets the value of the sentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSentTime(XMLGregorianCalendar value) {
        this.sentTime = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityType }
     *     
     */
    public SecurityType getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityType }
     *     
     */
    public void setSecurity(SecurityType value) {
        this.security = value;
    }

    /**
     * Gets the value of the senderSoftware property.
     * 
     * @return
     *     possible object is
     *     {@link SenderSoftwareType }
     *     
     */
    public SenderSoftwareType getSenderSoftware() {
        return senderSoftware;
    }

    /**
     * Sets the value of the senderSoftware property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderSoftwareType }
     *     
     */
    public void setSenderSoftware(SenderSoftwareType value) {
        this.senderSoftware = value;
    }

    /**
     * Gets the value of the mailbox property.
     * 
     * @return
     *     possible object is
     *     {@link MailboxType }
     *     
     */
    public MailboxType getMailbox() {
        return mailbox;
    }

    /**
     * Sets the value of the mailbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailboxType }
     *     
     */
    public void setMailbox(MailboxType value) {
        this.mailbox = value;
    }

    /**
     * Gets the value of the testMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestMessage() {
        return testMessage;
    }

    /**
     * Sets the value of the testMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestMessage(String value) {
        this.testMessage = value;
    }

    /**
     * Gets the value of the rxReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRxReferenceNumber() {
        return rxReferenceNumber;
    }

    /**
     * Sets the value of the rxReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRxReferenceNumber(String value) {
        this.rxReferenceNumber = value;
    }

    /**
     * Gets the value of the tertiaryIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTertiaryIdentifier() {
        return tertiaryIdentifier;
    }

    /**
     * Sets the value of the tertiaryIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTertiaryIdentifier(String value) {
        this.tertiaryIdentifier = value;
    }

    /**
     * Gets the value of the prescriberOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriberOrderNumber() {
        return prescriberOrderNumber;
    }

    /**
     * Sets the value of the prescriberOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriberOrderNumber(String value) {
        this.prescriberOrderNumber = value;
    }

    /**
     * Gets the value of the digitalSignature property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalSignature }
     *     
     */
    public DigitalSignature getDigitalSignature() {
        return digitalSignature;
    }

    /**
     * Sets the value of the digitalSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalSignature }
     *     
     */
    public void setDigitalSignature(DigitalSignature value) {
        this.digitalSignature = value;
    }

    /**
     * Gets the value of the prescriberOrderGroup property.
     * 
     * @return
     *     possible object is
     *     {@link OrderGroup }
     *     
     */
    public OrderGroup getPrescriberOrderGroup() {
        return prescriberOrderGroup;
    }

    /**
     * Sets the value of the prescriberOrderGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderGroup }
     *     
     */
    public void setPrescriberOrderGroup(OrderGroup value) {
        this.prescriberOrderGroup = value;
    }

    /**
     * Gets the value of the rxReferenceOrderGroup property.
     * 
     * @return
     *     possible object is
     *     {@link OrderGroup }
     *     
     */
    public OrderGroup getRxReferenceOrderGroup() {
        return rxReferenceOrderGroup;
    }

    /**
     * Sets the value of the rxReferenceOrderGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderGroup }
     *     
     */
    public void setRxReferenceOrderGroup(OrderGroup value) {
        this.rxReferenceOrderGroup = value;
    }

}
