//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Historical Reference used in Medication
 * 
 * <p>Java class for HistorySourceAbstract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistorySourceAbstract">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Source" type="{}SourceQualifier"/>
 *         &lt;element name="SourceReference" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="FillNumber" type="{}n2" minOccurs="0"/>
 *         &lt;element name="PaymentType" type="{}PaymentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistorySourceAbstract", propOrder = {
    "source",
    "sourceReference",
    "fillNumber",
    "paymentType"
})
@XmlSeeAlso({
    HistorySourceWithoutPayment.class,
    HistorySourceWithPayment.class
})
public class HistorySourceAbstract {

    @XmlElement(name = "Source", required = true)
    protected SourceQualifier source;
    @XmlElement(name = "SourceReference")
    protected String sourceReference;
    @XmlElement(name = "FillNumber")
    protected String fillNumber;
    @XmlElement(name = "PaymentType")
    protected String paymentType;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceQualifier }
     *     
     */
    public SourceQualifier getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceQualifier }
     *     
     */
    public void setSource(SourceQualifier value) {
        this.source = value;
    }

    /**
     * Gets the value of the sourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceReference() {
        return sourceReference;
    }

    /**
     * Sets the value of the sourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceReference(String value) {
        this.sourceReference = value;
    }

    /**
     * Gets the value of the fillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFillNumber() {
        return fillNumber;
    }

    /**
     * Sets the value of the fillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFillNumber(String value) {
        this.fillNumber = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentType(String value) {
        this.paymentType = value;
    }

}
