//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryPrescribedMedication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryPrescribedMedication">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DrugDescription" type="{}an1..105"/>
 *         &lt;element name="DrugCoded" type="{}DrugCoded" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{}Quantity"/>
 *         &lt;element name="DaysSupply" type="{}n1..3" minOccurs="0"/>
 *         &lt;element name="WrittenDate" type="{}DateType"/>
 *         &lt;element name="LastFillDate" type="{}DateType" minOccurs="0"/>
 *         &lt;element name="Substitutions" type="{}SubstitutionCode"/>
 *         &lt;element name="NumberOfRefills" type="{}n1..2"/>
 *         &lt;element name="Diagnosis" type="{}DiagnosisRestricted" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="PriorAuthorization" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="Note" type="{}an1..210" minOccurs="0"/>
 *         &lt;element name="DrugUseEvaluation" type="{}DrugUseEvaluation" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="DrugCoverageStatusCode" type="{}DrugCoverageStatusCode" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="PriorAuthorizationStatus" type="{}PriorAuthorizationStatus" minOccurs="0"/>
 *         &lt;element name="Sig" type="{}Sig" minOccurs="0"/>
 *         &lt;element name="PharmacyRequestedRefills" type="{}n1..2" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="DoNotFill" type="{}DoNotFill" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="TimeZone" type="{}TimeZone" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="RefillsRemaining" type="{}n1..2" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="HistoryPrescriberOrderNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="OrderCaptureMethod" type="{}OrderCaptureMethod" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Pharmacy" type="{}OptionalPharmacy" minOccurs="0"/>
 *         &lt;element name="Prescriber" type="{}HistoryPrescriberChoice" minOccurs="0"/>
 *         &lt;element name="HistorySource" type="{}HistorySourceWithoutPayment" minOccurs="0"/>
 *         &lt;element name="ReasonForSubstitutionCodeUsed" type="{}ReasonForSubstitutionCodeUsed" minOccurs="0"/>
 *         &lt;element name="SplitScript" type="{}SplitScript" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ManufacturerName" type="{}an1..105" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="LotNumber" type="{}LotNumber" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="RxFillIndicator" type="{}RxFillIndicator" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Patient" type="{}Patient" minOccurs="0"/>
 *         &lt;element name="Wound" type="{}WoundStructure" maxOccurs="9" minOccurs="0"/>
 *         &lt;element name="CompoundInformation" type="{}CompoundLotNotUsed" minOccurs="0"/>
 *         &lt;element name="NumberOfPackagesToBeDispensed" type="{}n1..2" minOccurs="0"/>
 *         &lt;element name="OtherMedicationDate" type="{}OtherMedicationDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NeedNoLaterThan" type="{}NeedNoLaterThan" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ProviderExplicitAuthorizationToAdminister" type="{}BooleanCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryPrescribedMedication", propOrder = {
    "drugDescription",
    "drugCoded",
    "quantity",
    "daysSupply",
    "writtenDate",
    "lastFillDate",
    "substitutions",
    "numberOfRefills",
    "diagnosis",
    "priorAuthorization",
    "note",
    "drugUseEvaluation",
    "drugCoverageStatusCode",
    "priorAuthorizationStatus",
    "sig",
    "historyPrescriberOrderNumber",
    "pharmacy",
    "prescriber",
    "historySource",
    "reasonForSubstitutionCodeUsed",
    "patient",
    "wound",
    "compoundInformation",
    "numberOfPackagesToBeDispensed",
    "otherMedicationDate",
    "providerExplicitAuthorizationToAdminister"
})
public class HistoryPrescribedMedication {

    @XmlElement(name = "DrugDescription", required = true)
    protected String drugDescription;
    @XmlElement(name = "DrugCoded")
    protected DrugCoded drugCoded;
    @XmlElement(name = "Quantity", required = true)
    protected Quantity quantity;
    @XmlElement(name = "DaysSupply")
    protected String daysSupply;
    @XmlElement(name = "WrittenDate", required = true)
    protected DateType writtenDate;
    @XmlElement(name = "LastFillDate")
    protected DateType lastFillDate;
    @XmlElement(name = "Substitutions", required = true)
    protected String substitutions;
    @XmlElement(name = "NumberOfRefills", required = true)
    protected String numberOfRefills;
    @XmlElement(name = "Diagnosis")
    protected List<DiagnosisRestricted> diagnosis;
    @XmlElement(name = "PriorAuthorization")
    protected String priorAuthorization;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "DrugUseEvaluation")
    protected List<DrugUseEvaluation> drugUseEvaluation;
    @XmlElement(name = "DrugCoverageStatusCode")
    @XmlSchemaType(name = "string")
    protected List<DrugCoverageStatusCode> drugCoverageStatusCode;
    @XmlElement(name = "PriorAuthorizationStatus")
    @XmlSchemaType(name = "string")
    protected PriorAuthorizationStatus priorAuthorizationStatus;
    @XmlElement(name = "Sig")
    protected Sig sig;
    @XmlElement(name = "HistoryPrescriberOrderNumber")
    protected String historyPrescriberOrderNumber;
    @XmlElement(name = "Pharmacy")
    protected OptionalPharmacy pharmacy;
    @XmlElement(name = "Prescriber")
    protected HistoryPrescriberChoice prescriber;
    @XmlElement(name = "HistorySource")
    protected HistorySourceWithoutPayment historySource;
    @XmlElement(name = "ReasonForSubstitutionCodeUsed")
    @XmlSchemaType(name = "string")
    protected ReasonForSubstitutionCodeUsed reasonForSubstitutionCodeUsed;
    @XmlElement(name = "Patient")
    protected Patient patient;
    @XmlElement(name = "Wound")
    protected List<WoundStructure> wound;
    @XmlElement(name = "CompoundInformation")
    protected CompoundLotNotUsed compoundInformation;
    @XmlElement(name = "NumberOfPackagesToBeDispensed")
    protected String numberOfPackagesToBeDispensed;
    @XmlElement(name = "OtherMedicationDate")
    protected List<OtherMedicationDate> otherMedicationDate;
    @XmlElement(name = "ProviderExplicitAuthorizationToAdminister")
    @XmlSchemaType(name = "string")
    protected BooleanCode providerExplicitAuthorizationToAdminister;

    /**
     * Gets the value of the drugDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugDescription() {
        return drugDescription;
    }

    /**
     * Sets the value of the drugDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugDescription(String value) {
        this.drugDescription = value;
    }

    /**
     * Gets the value of the drugCoded property.
     * 
     * @return
     *     possible object is
     *     {@link DrugCoded }
     *     
     */
    public DrugCoded getDrugCoded() {
        return drugCoded;
    }

    /**
     * Sets the value of the drugCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugCoded }
     *     
     */
    public void setDrugCoded(DrugCoded value) {
        this.drugCoded = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setQuantity(Quantity value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the daysSupply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysSupply() {
        return daysSupply;
    }

    /**
     * Sets the value of the daysSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysSupply(String value) {
        this.daysSupply = value;
    }

    /**
     * Gets the value of the writtenDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getWrittenDate() {
        return writtenDate;
    }

    /**
     * Sets the value of the writtenDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setWrittenDate(DateType value) {
        this.writtenDate = value;
    }

    /**
     * Gets the value of the lastFillDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getLastFillDate() {
        return lastFillDate;
    }

    /**
     * Sets the value of the lastFillDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setLastFillDate(DateType value) {
        this.lastFillDate = value;
    }

    /**
     * Gets the value of the substitutions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstitutions() {
        return substitutions;
    }

    /**
     * Sets the value of the substitutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstitutions(String value) {
        this.substitutions = value;
    }

    /**
     * Gets the value of the numberOfRefills property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfRefills() {
        return numberOfRefills;
    }

    /**
     * Sets the value of the numberOfRefills property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfRefills(String value) {
        this.numberOfRefills = value;
    }

    /**
     * Gets the value of the diagnosis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiagnosisRestricted }
     * 
     * 
     */
    public List<DiagnosisRestricted> getDiagnosis() {
        if (diagnosis == null) {
            diagnosis = new ArrayList<DiagnosisRestricted>();
        }
        return this.diagnosis;
    }

    /**
     * Gets the value of the priorAuthorization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorAuthorization() {
        return priorAuthorization;
    }

    /**
     * Sets the value of the priorAuthorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorAuthorization(String value) {
        this.priorAuthorization = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the drugUseEvaluation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drugUseEvaluation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrugUseEvaluation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DrugUseEvaluation }
     * 
     * 
     */
    public List<DrugUseEvaluation> getDrugUseEvaluation() {
        if (drugUseEvaluation == null) {
            drugUseEvaluation = new ArrayList<DrugUseEvaluation>();
        }
        return this.drugUseEvaluation;
    }

    /**
     * Gets the value of the drugCoverageStatusCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drugCoverageStatusCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrugCoverageStatusCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DrugCoverageStatusCode }
     * 
     * 
     */
    public List<DrugCoverageStatusCode> getDrugCoverageStatusCode() {
        if (drugCoverageStatusCode == null) {
            drugCoverageStatusCode = new ArrayList<DrugCoverageStatusCode>();
        }
        return this.drugCoverageStatusCode;
    }

    /**
     * Gets the value of the priorAuthorizationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PriorAuthorizationStatus }
     *     
     */
    public PriorAuthorizationStatus getPriorAuthorizationStatus() {
        return priorAuthorizationStatus;
    }

    /**
     * Sets the value of the priorAuthorizationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorAuthorizationStatus }
     *     
     */
    public void setPriorAuthorizationStatus(PriorAuthorizationStatus value) {
        this.priorAuthorizationStatus = value;
    }

    /**
     * Gets the value of the sig property.
     * 
     * @return
     *     possible object is
     *     {@link Sig }
     *     
     */
    public Sig getSig() {
        return sig;
    }

    /**
     * Sets the value of the sig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sig }
     *     
     */
    public void setSig(Sig value) {
        this.sig = value;
    }

    /**
     * Gets the value of the historyPrescriberOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHistoryPrescriberOrderNumber() {
        return historyPrescriberOrderNumber;
    }

    /**
     * Sets the value of the historyPrescriberOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHistoryPrescriberOrderNumber(String value) {
        this.historyPrescriberOrderNumber = value;
    }

    /**
     * Gets the value of the pharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalPharmacy }
     *     
     */
    public OptionalPharmacy getPharmacy() {
        return pharmacy;
    }

    /**
     * Sets the value of the pharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalPharmacy }
     *     
     */
    public void setPharmacy(OptionalPharmacy value) {
        this.pharmacy = value;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryPrescriberChoice }
     *     
     */
    public HistoryPrescriberChoice getPrescriber() {
        return prescriber;
    }

    /**
     * Sets the value of the prescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryPrescriberChoice }
     *     
     */
    public void setPrescriber(HistoryPrescriberChoice value) {
        this.prescriber = value;
    }

    /**
     * Gets the value of the historySource property.
     * 
     * @return
     *     possible object is
     *     {@link HistorySourceWithoutPayment }
     *     
     */
    public HistorySourceWithoutPayment getHistorySource() {
        return historySource;
    }

    /**
     * Sets the value of the historySource property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistorySourceWithoutPayment }
     *     
     */
    public void setHistorySource(HistorySourceWithoutPayment value) {
        this.historySource = value;
    }

    /**
     * Gets the value of the reasonForSubstitutionCodeUsed property.
     * 
     * @return
     *     possible object is
     *     {@link ReasonForSubstitutionCodeUsed }
     *     
     */
    public ReasonForSubstitutionCodeUsed getReasonForSubstitutionCodeUsed() {
        return reasonForSubstitutionCodeUsed;
    }

    /**
     * Sets the value of the reasonForSubstitutionCodeUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReasonForSubstitutionCodeUsed }
     *     
     */
    public void setReasonForSubstitutionCodeUsed(ReasonForSubstitutionCodeUsed value) {
        this.reasonForSubstitutionCodeUsed = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Patient }
     *     
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patient }
     *     
     */
    public void setPatient(Patient value) {
        this.patient = value;
    }

    /**
     * Gets the value of the wound property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wound property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWound().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WoundStructure }
     * 
     * 
     */
    public List<WoundStructure> getWound() {
        if (wound == null) {
            wound = new ArrayList<WoundStructure>();
        }
        return this.wound;
    }

    /**
     * Gets the value of the compoundInformation property.
     * 
     * @return
     *     possible object is
     *     {@link CompoundLotNotUsed }
     *     
     */
    public CompoundLotNotUsed getCompoundInformation() {
        return compoundInformation;
    }

    /**
     * Sets the value of the compoundInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompoundLotNotUsed }
     *     
     */
    public void setCompoundInformation(CompoundLotNotUsed value) {
        this.compoundInformation = value;
    }

    /**
     * Gets the value of the numberOfPackagesToBeDispensed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfPackagesToBeDispensed() {
        return numberOfPackagesToBeDispensed;
    }

    /**
     * Sets the value of the numberOfPackagesToBeDispensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfPackagesToBeDispensed(String value) {
        this.numberOfPackagesToBeDispensed = value;
    }

    /**
     * Gets the value of the otherMedicationDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherMedicationDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherMedicationDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherMedicationDate }
     * 
     * 
     */
    public List<OtherMedicationDate> getOtherMedicationDate() {
        if (otherMedicationDate == null) {
            otherMedicationDate = new ArrayList<OtherMedicationDate>();
        }
        return this.otherMedicationDate;
    }

    /**
     * Gets the value of the providerExplicitAuthorizationToAdminister property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanCode }
     *     
     */
    public BooleanCode getProviderExplicitAuthorizationToAdminister() {
        return providerExplicitAuthorizationToAdminister;
    }

    /**
     * Sets the value of the providerExplicitAuthorizationToAdminister property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanCode }
     *     
     */
    public void setProviderExplicitAuthorizationToAdminister(BooleanCode value) {
        this.providerExplicitAuthorizationToAdminister = value;
    }

}
