//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Drug Composition Structure
 * 
 * <p>Java class for IngredientLotNotUsedForPAandREM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IngredientLotNotUsedForPAandREM">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompoundIngredientItemDescription" type="{}an1..105"/>
 *         &lt;element name="ItemNumber" type="{}ProductCodeExtended" minOccurs="0"/>
 *         &lt;element name="Strength" type="{}Strength" minOccurs="0"/>
 *         &lt;element name="DEASchedule" type="{}NCICode" minOccurs="0"/>
 *         &lt;element name="LotNumber" type="{}LotNumber" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IngredientLotNotUsedForPAandREM", propOrder = {
    "compoundIngredientItemDescription",
    "itemNumber",
    "strength",
    "deaSchedule"
})
public class IngredientLotNotUsedForPAandREM {

    @XmlElement(name = "CompoundIngredientItemDescription", required = true)
    protected String compoundIngredientItemDescription;
    @XmlElement(name = "ItemNumber")
    protected ProductCodeExtended itemNumber;
    @XmlElement(name = "Strength")
    protected Strength strength;
    @XmlElement(name = "DEASchedule")
    protected NCICode deaSchedule;

    /**
     * Gets the value of the compoundIngredientItemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompoundIngredientItemDescription() {
        return compoundIngredientItemDescription;
    }

    /**
     * Sets the value of the compoundIngredientItemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompoundIngredientItemDescription(String value) {
        this.compoundIngredientItemDescription = value;
    }

    /**
     * Gets the value of the itemNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCodeExtended }
     *     
     */
    public ProductCodeExtended getItemNumber() {
        return itemNumber;
    }

    /**
     * Sets the value of the itemNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCodeExtended }
     *     
     */
    public void setItemNumber(ProductCodeExtended value) {
        this.itemNumber = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link Strength }
     *     
     */
    public Strength getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Strength }
     *     
     */
    public void setStrength(Strength value) {
        this.strength = value;
    }

    /**
     * Gets the value of the deaSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link NCICode }
     *     
     */
    public NCICode getDEASchedule() {
        return deaSchedule;
    }

    /**
     * Sets the value of the deaSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link NCICode }
     *     
     */
    public void setDEASchedule(NCICode value) {
        this.deaSchedule = value;
    }

}
