//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasurementDurationTriggerTiming complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasurementDurationTriggerTiming">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MeasurementTrigger" type="{}SigCode"/>
 *         &lt;element name="MeasurementDurationClarifyingFreeText" type="{}an1..255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasurementDurationTriggerTiming", propOrder = {
    "measurementTrigger",
    "measurementDurationClarifyingFreeText"
})
public class MeasurementDurationTriggerTiming {

    @XmlElement(name = "MeasurementTrigger", required = true)
    protected SigCode measurementTrigger;
    @XmlElement(name = "MeasurementDurationClarifyingFreeText")
    protected String measurementDurationClarifyingFreeText;

    /**
     * Gets the value of the measurementTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link SigCode }
     *     
     */
    public SigCode getMeasurementTrigger() {
        return measurementTrigger;
    }

    /**
     * Sets the value of the measurementTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link SigCode }
     *     
     */
    public void setMeasurementTrigger(SigCode value) {
        this.measurementTrigger = value;
    }

    /**
     * Gets the value of the measurementDurationClarifyingFreeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementDurationClarifyingFreeText() {
        return measurementDurationClarifyingFreeText;
    }

    /**
     * Sets the value of the measurementDurationClarifyingFreeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementDurationClarifyingFreeText(String value) {
        this.measurementDurationClarifyingFreeText = value;
    }

}
