//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageRequestSubCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageRequestSubCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="J"/>
 *     &lt;enumeration value="K"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="M"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MessageRequestSubCode")
@XmlEnum
public enum MessageRequestSubCode {


    /**
     * Prescriber must confirm their State license status.
     * 
     */
    A,

    /**
     * Prescriber must confirm their DEA license status in prescribing state.
     * 
     */
    B,

    /**
     * Prescriber must confirm their DEA registration by DEA class.
     * 
     */
    C,

    /**
     * Prescriber must confirm their State Controlled Substance Registration license status.
     * 
     */
    D,

    /**
     * Prescriber must confirm their registration by State Controlled Substance Registration class.
     * 
     */
    E,

    /**
     * Prescriber must confirm their NADEAN license status.
     * 
     */
    F,

    /**
     * Prescriber must obtain/validate Type1 NPI.
     * 
     */
    G,

    /**
     * Prescriber must enroll/re-enroll with prescription benefit plan.
     * 
     */
    H,

    /**
     * Prescriber must confirm prescriptive authority criteria for prescribed medication is met.
     * 
     */
    I,

    /**
     * Prescriber must enroll/re-enroll in REMS. 
     * 
     */
    J,

    /**
     * Prescriber must confirm their assignment as patients’ lock-in prescriber.
     * 
     */
    K,

    /**
     * Prescriber must obtain/validate their supervising prescriber.
     * 
     */
    L,

    /**
     * Prescriber must confirm their Certificate to Prescribe Number status.
     * 
     */
    M;

    public String value() {
        return name();
    }

    public static MessageRequestSubCode fromValue(String v) {
        return valueOf(v);
    }

}
