//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="Body" type="{}BodyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DatatypesVersion" use="required" type="{}an" />
 *       &lt;attribute name="TransportVersion" use="required" type="{}an" />
 *       &lt;attribute name="TransactionDomain" use="required" type="{}TransactionDomain" />
 *       &lt;attribute name="TransactionVersion" use="required" type="{}an" />
 *       &lt;attribute name="StructuresVersion" use="required" type="{}an" />
 *       &lt;attribute name="ECLVersion" use="required" type="{}an" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Message")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageType", propOrder = {
    "header",
    "body"
})
public class MessageType {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Body", required = true)
    protected BodyType body;
    @XmlAttribute(name = "DatatypesVersion", required = true)
    protected String datatypesVersion;
    @XmlAttribute(name = "TransportVersion", required = true)
    protected String transportVersion;
    @XmlAttribute(name = "TransactionDomain", required = true)
    protected TransactionDomain transactionDomain;
    @XmlAttribute(name = "TransactionVersion", required = true)
    protected String transactionVersion;
    @XmlAttribute(name = "StructuresVersion", required = true)
    protected String structuresVersion;
    @XmlAttribute(name = "ECLVersion", required = true)
    protected String eclVersion;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link BodyType }
     *     
     */
    public BodyType getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyType }
     *     
     */
    public void setBody(BodyType value) {
        this.body = value;
    }

    /**
     * Gets the value of the datatypesVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatatypesVersion() {
        return datatypesVersion;
    }

    /**
     * Sets the value of the datatypesVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatatypesVersion(String value) {
        this.datatypesVersion = value;
    }

    /**
     * Gets the value of the transportVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportVersion() {
        return transportVersion;
    }

    /**
     * Sets the value of the transportVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportVersion(String value) {
        this.transportVersion = value;
    }

    /**
     * Gets the value of the transactionDomain property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionDomain }
     *     
     */
    public TransactionDomain getTransactionDomain() {
        return transactionDomain;
    }

    /**
     * Sets the value of the transactionDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionDomain }
     *     
     */
    public void setTransactionDomain(TransactionDomain value) {
        this.transactionDomain = value;
    }

    /**
     * Gets the value of the transactionVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionVersion() {
        return transactionVersion;
    }

    /**
     * Sets the value of the transactionVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionVersion(String value) {
        this.transactionVersion = value;
    }

    /**
     * Gets the value of the structuresVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStructuresVersion() {
        return structuresVersion;
    }

    /**
     * Sets the value of the structuresVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStructuresVersion(String value) {
        this.structuresVersion = value;
    }

    /**
     * Gets the value of the eclVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECLVersion() {
        return eclVersion;
    }

    /**
     * Sets the value of the eclVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECLVersion(String value) {
        this.eclVersion = value;
    }

}
