//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Prescribed or Dispensed may only occur once, according to appropriate need in a transaction. A transaction may contain a loop of Prescribed and Dispensed for example, in the RxChangeRequest, where the prescriber prescribed x and the pharmacy filled y. But a transaction may not contain multiple Prescribed and Dispensed.
 * 
 * 
 * 
 * <p>Java class for NewRxRequestMedication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewRxRequestMedication">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DrugDescription" type="{}an1..105"/>
 *         &lt;element name="DrugCoded" type="{}DrugCoded" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{}Quantity" minOccurs="0"/>
 *         &lt;element name="DaysSupply" type="{}n1..3" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="WrittenDate" type="{}DateType" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="LastFillDate" type="{}DateType" minOccurs="0"/>
 *         &lt;element name="Substitutions" type="{}SubstitutionCode" minOccurs="0"/>
 *         &lt;element name="NumberOfRefills" type="{}n1..2" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Diagnosis" type="{}DiagnosisRestricted" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="PriorAuthorization" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Note" type="{}an1..210" minOccurs="0"/>
 *         &lt;element name="DrugUseEvaluation" type="{}DrugUseEvaluation" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="DrugCoverageStatusCode" type="{}DrugCoverageStatusCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="PriorAuthorizationStatus" type="{}PriorAuthorizationStatus" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Sig" type="{}Sig" minOccurs="0"/>
 *         &lt;element name="PharmacyRequestedRefills" type="{}n1..2" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="DoNotFill" type="{}DoNotFill" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="TimeZone" type="{}TimeZone" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="RefillsRemaining" type="{}n1..2" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="HistoryPrescriberOrderNumber" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="OrderCaptureMethod" type="{}OrderCaptureMethod" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Pharmacy" type="{}OptionalPharmacy" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Prescriber" type="{}HistoryPrescriberChoice" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="HistorySource" type="{}HistorySourceWithoutPayment" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ReasonForSubstitutionCodeUsed" type="{}ReasonForSubstitutionCodeUsed" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="SplitScript" type="{}SplitScript" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ManufacturerName" type="{}an1..105" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="LotNumber" type="{}LotNumber" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="RxFillIndicator" type="{}RxFillIndicator" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Service" type="{}ServiceStructure" minOccurs="0"/>
 *         &lt;element name="IVAdministration" type="{}IVAdministrationType" minOccurs="0"/>
 *         &lt;element name="TreatmentIndicator" type="{}TreatmentIndicator" minOccurs="0"/>
 *         &lt;element name="ProphylacticOrEpisodic" type="{}ProphylacticOrEpisodic" minOccurs="0"/>
 *         &lt;element name="CurrentTreatmentCycle" type="{}n1..2" minOccurs="0"/>
 *         &lt;element name="NumberOfCyclesPlanned" type="{}n1..2" minOccurs="0"/>
 *         &lt;element name="CompoundInformation" type="{}CompoundLotNotUsed" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="NumberOfPackagesToBeDispensed" type="{}n1..2" minOccurs="0"/>
 *         &lt;element name="OtherMedicationDate" type="{}OtherMedicationDate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NeedNoLaterThan" type="{}NeedNoLaterThan" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewRxRequestMedication", propOrder = {
    "drugDescription",
    "drugCoded",
    "quantity",
    "lastFillDate",
    "substitutions",
    "diagnosis",
    "note",
    "sig",
    "service",
    "ivAdministration",
    "treatmentIndicator",
    "prophylacticOrEpisodic",
    "currentTreatmentCycle",
    "numberOfCyclesPlanned",
    "numberOfPackagesToBeDispensed",
    "otherMedicationDate"
})
public class NewRxRequestMedication {

    @XmlElement(name = "DrugDescription", required = true)
    protected String drugDescription;
    @XmlElement(name = "DrugCoded")
    protected DrugCoded drugCoded;
    @XmlElement(name = "Quantity")
    protected Quantity quantity;
    @XmlElement(name = "LastFillDate")
    protected DateType lastFillDate;
    @XmlElement(name = "Substitutions")
    protected String substitutions;
    @XmlElement(name = "Diagnosis")
    protected List<DiagnosisRestricted> diagnosis;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "Sig")
    protected Sig sig;
    @XmlElement(name = "Service")
    protected ServiceStructure service;
    @XmlElement(name = "IVAdministration")
    protected IVAdministrationType ivAdministration;
    @XmlElement(name = "TreatmentIndicator")
    @XmlSchemaType(name = "string")
    protected TreatmentIndicator treatmentIndicator;
    @XmlElement(name = "ProphylacticOrEpisodic")
    @XmlSchemaType(name = "string")
    protected ProphylacticOrEpisodic prophylacticOrEpisodic;
    @XmlElement(name = "CurrentTreatmentCycle")
    protected String currentTreatmentCycle;
    @XmlElement(name = "NumberOfCyclesPlanned")
    protected String numberOfCyclesPlanned;
    @XmlElement(name = "NumberOfPackagesToBeDispensed")
    protected String numberOfPackagesToBeDispensed;
    @XmlElement(name = "OtherMedicationDate")
    protected List<OtherMedicationDate> otherMedicationDate;

    /**
     * Gets the value of the drugDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugDescription() {
        return drugDescription;
    }

    /**
     * Sets the value of the drugDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugDescription(String value) {
        this.drugDescription = value;
    }

    /**
     * Gets the value of the drugCoded property.
     * 
     * @return
     *     possible object is
     *     {@link DrugCoded }
     *     
     */
    public DrugCoded getDrugCoded() {
        return drugCoded;
    }

    /**
     * Sets the value of the drugCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugCoded }
     *     
     */
    public void setDrugCoded(DrugCoded value) {
        this.drugCoded = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setQuantity(Quantity value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the lastFillDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getLastFillDate() {
        return lastFillDate;
    }

    /**
     * Sets the value of the lastFillDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setLastFillDate(DateType value) {
        this.lastFillDate = value;
    }

    /**
     * Gets the value of the substitutions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstitutions() {
        return substitutions;
    }

    /**
     * Sets the value of the substitutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstitutions(String value) {
        this.substitutions = value;
    }

    /**
     * Gets the value of the diagnosis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiagnosisRestricted }
     * 
     * 
     */
    public List<DiagnosisRestricted> getDiagnosis() {
        if (diagnosis == null) {
            diagnosis = new ArrayList<DiagnosisRestricted>();
        }
        return this.diagnosis;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the sig property.
     * 
     * @return
     *     possible object is
     *     {@link Sig }
     *     
     */
    public Sig getSig() {
        return sig;
    }

    /**
     * Sets the value of the sig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sig }
     *     
     */
    public void setSig(Sig value) {
        this.sig = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceStructure }
     *     
     */
    public ServiceStructure getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceStructure }
     *     
     */
    public void setService(ServiceStructure value) {
        this.service = value;
    }

    /**
     * Gets the value of the ivAdministration property.
     * 
     * @return
     *     possible object is
     *     {@link IVAdministrationType }
     *     
     */
    public IVAdministrationType getIVAdministration() {
        return ivAdministration;
    }

    /**
     * Sets the value of the ivAdministration property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVAdministrationType }
     *     
     */
    public void setIVAdministration(IVAdministrationType value) {
        this.ivAdministration = value;
    }

    /**
     * Gets the value of the treatmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link TreatmentIndicator }
     *     
     */
    public TreatmentIndicator getTreatmentIndicator() {
        return treatmentIndicator;
    }

    /**
     * Sets the value of the treatmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreatmentIndicator }
     *     
     */
    public void setTreatmentIndicator(TreatmentIndicator value) {
        this.treatmentIndicator = value;
    }

    /**
     * Gets the value of the prophylacticOrEpisodic property.
     * 
     * @return
     *     possible object is
     *     {@link ProphylacticOrEpisodic }
     *     
     */
    public ProphylacticOrEpisodic getProphylacticOrEpisodic() {
        return prophylacticOrEpisodic;
    }

    /**
     * Sets the value of the prophylacticOrEpisodic property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProphylacticOrEpisodic }
     *     
     */
    public void setProphylacticOrEpisodic(ProphylacticOrEpisodic value) {
        this.prophylacticOrEpisodic = value;
    }

    /**
     * Gets the value of the currentTreatmentCycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentTreatmentCycle() {
        return currentTreatmentCycle;
    }

    /**
     * Sets the value of the currentTreatmentCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentTreatmentCycle(String value) {
        this.currentTreatmentCycle = value;
    }

    /**
     * Gets the value of the numberOfCyclesPlanned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfCyclesPlanned() {
        return numberOfCyclesPlanned;
    }

    /**
     * Sets the value of the numberOfCyclesPlanned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfCyclesPlanned(String value) {
        this.numberOfCyclesPlanned = value;
    }

    /**
     * Gets the value of the numberOfPackagesToBeDispensed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfPackagesToBeDispensed() {
        return numberOfPackagesToBeDispensed;
    }

    /**
     * Sets the value of the numberOfPackagesToBeDispensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfPackagesToBeDispensed(String value) {
        this.numberOfPackagesToBeDispensed = value;
    }

    /**
     * Gets the value of the otherMedicationDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherMedicationDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherMedicationDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherMedicationDate }
     * 
     * 
     */
    public List<OtherMedicationDate> getOtherMedicationDate() {
        if (otherMedicationDate == null) {
            otherMedicationDate = new ArrayList<OtherMedicationDate>();
        }
        return this.otherMedicationDate;
    }

}
