//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonHumanPatient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NonHumanPatient">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identification" type="{}PatientID" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Name" type="{}NonHumanNameType"/>
 *         &lt;element name="Gender" type="{}Gender"/>
 *         &lt;element name="DateOfBirth" type="{}DateType"/>
 *         &lt;element name="Address" type="{}AddressType" minOccurs="0"/>
 *         &lt;element name="CommunicationNumbers" type="{}CommunicationNumbersType" minOccurs="0"/>
 *         &lt;element name="PatientLocation" type="{}PatientLocation" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="LanguageNameCode" type="{}an1..3" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ResidenceCode" type="{}ResidenceCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="PregnancyIndicator" type="{}BooleanCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Race" type="{}CDCCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Ethnicity" type="{}CDCCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Species" type="{}SNOMEDCodeTextMandatory"/>
 *         &lt;element name="AlternateContact" type="{}AlternateContactStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonHumanPatient", propOrder = {
    "name",
    "gender",
    "dateOfBirth",
    "address",
    "communicationNumbers",
    "species",
    "alternateContact"
})
public class NonHumanPatient {

    @XmlElement(name = "Name", required = true)
    protected NonHumanNameType name;
    @XmlElement(name = "Gender", required = true)
    @XmlSchemaType(name = "string")
    protected Gender gender;
    @XmlElement(name = "DateOfBirth", required = true)
    protected DateType dateOfBirth;
    @XmlElement(name = "Address")
    protected AddressType address;
    @XmlElement(name = "CommunicationNumbers")
    protected CommunicationNumbersType communicationNumbers;
    @XmlElement(name = "Species", required = true)
    protected SNOMEDCodeTextMandatory species;
    @XmlElement(name = "AlternateContact")
    protected AlternateContactStructure alternateContact;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NonHumanNameType }
     *     
     */
    public NonHumanNameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonHumanNameType }
     *     
     */
    public void setName(NonHumanNameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDateOfBirth(DateType value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the communicationNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationNumbersType }
     *     
     */
    public CommunicationNumbersType getCommunicationNumbers() {
        return communicationNumbers;
    }

    /**
     * Sets the value of the communicationNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationNumbersType }
     *     
     */
    public void setCommunicationNumbers(CommunicationNumbersType value) {
        this.communicationNumbers = value;
    }

    /**
     * Gets the value of the species property.
     * 
     * @return
     *     possible object is
     *     {@link SNOMEDCodeTextMandatory }
     *     
     */
    public SNOMEDCodeTextMandatory getSpecies() {
        return species;
    }

    /**
     * Sets the value of the species property.
     * 
     * @param value
     *     allowed object is
     *     {@link SNOMEDCodeTextMandatory }
     *     
     */
    public void setSpecies(SNOMEDCodeTextMandatory value) {
        this.species = value;
    }

    /**
     * Gets the value of the alternateContact property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateContactStructure }
     *     
     */
    public AlternateContactStructure getAlternateContact() {
        return alternateContact;
    }

    /**
     * Sets the value of the alternateContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateContactStructure }
     *     
     */
    public void setAlternateContact(AlternateContactStructure value) {
        this.alternateContact = value;
    }

}
