//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NumericValueSimpleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumericValueSimpleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ComparisonOperator" type="{}ComparisonOperator"/>
 *         &lt;element name="ComparisonValue" type="{}sn1..18"/>
 *         &lt;element name="NextQuestionID" type="{}an1..35"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumericValueSimpleType", propOrder = {
    "comparisonOperator",
    "comparisonValue",
    "nextQuestionID"
})
public class NumericValueSimpleType {

    @XmlElement(name = "ComparisonOperator", required = true)
    @XmlSchemaType(name = "string")
    protected ComparisonOperator comparisonOperator;
    @XmlElement(name = "ComparisonValue", required = true)
    protected String comparisonValue;
    @XmlElement(name = "NextQuestionID", required = true)
    protected String nextQuestionID;

    /**
     * Gets the value of the comparisonOperator property.
     * 
     * @return
     *     possible object is
     *     {@link ComparisonOperator }
     *     
     */
    public ComparisonOperator getComparisonOperator() {
        return comparisonOperator;
    }

    /**
     * Sets the value of the comparisonOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparisonOperator }
     *     
     */
    public void setComparisonOperator(ComparisonOperator value) {
        this.comparisonOperator = value;
    }

    /**
     * Gets the value of the comparisonValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComparisonValue() {
        return comparisonValue;
    }

    /**
     * Sets the value of the comparisonValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComparisonValue(String value) {
        this.comparisonValue = value;
    }

    /**
     * Gets the value of the nextQuestionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextQuestionID() {
        return nextQuestionID;
    }

    /**
     * Sets the value of the nextQuestionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextQuestionID(String value) {
        this.nextQuestionID = value;
    }

}
