//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PAAppealRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PAAppealRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PACaseID" type="{}an1..35"/>
 *         &lt;element name="AppealCaseID" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="DeadlineForReply" type="{}DateType" minOccurs="0"/>
 *         &lt;element name="QuestionSet" type="{}QuestionSetGroupForRequest" minOccurs="0"/>
 *         &lt;element name="PANote" type="{}an1..2000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PAAppealRequestType", propOrder = {
    "paCaseID",
    "appealCaseID",
    "deadlineForReply",
    "questionSet",
    "paNote"
})
public class PAAppealRequestType {

    @XmlElement(name = "PACaseID", required = true)
    protected String paCaseID;
    @XmlElement(name = "AppealCaseID")
    protected String appealCaseID;
    @XmlElement(name = "DeadlineForReply")
    protected DateType deadlineForReply;
    @XmlElement(name = "QuestionSet")
    protected QuestionSetGroupForRequest questionSet;
    @XmlElement(name = "PANote")
    protected String paNote;

    /**
     * Gets the value of the paCaseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACaseID() {
        return paCaseID;
    }

    /**
     * Sets the value of the paCaseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACaseID(String value) {
        this.paCaseID = value;
    }

    /**
     * Gets the value of the appealCaseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppealCaseID() {
        return appealCaseID;
    }

    /**
     * Sets the value of the appealCaseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppealCaseID(String value) {
        this.appealCaseID = value;
    }

    /**
     * Gets the value of the deadlineForReply property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDeadlineForReply() {
        return deadlineForReply;
    }

    /**
     * Sets the value of the deadlineForReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDeadlineForReply(DateType value) {
        this.deadlineForReply = value;
    }

    /**
     * Gets the value of the questionSet property.
     * 
     * @return
     *     possible object is
     *     {@link QuestionSetGroupForRequest }
     *     
     */
    public QuestionSetGroupForRequest getQuestionSet() {
        return questionSet;
    }

    /**
     * Sets the value of the questionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuestionSetGroupForRequest }
     *     
     */
    public void setQuestionSet(QuestionSetGroupForRequest value) {
        this.questionSet = value;
    }

    /**
     * Gets the value of the paNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPANote() {
        return paNote;
    }

    /**
     * Sets the value of the paNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPANote(String value) {
        this.paNote = value;
    }

}
