//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PACancelRequestStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PACancelRequestStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PACaseID" type="{}an1..35"/>
 *         &lt;element name="CancelReasonCode" type="{}ReasonCode13" minOccurs="0"/>
 *         &lt;element name="IsPatientNotified" type="{}BooleanCode" minOccurs="0"/>
 *         &lt;element name="PANote" type="{}an1..2000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PACancelRequestStructure", propOrder = {
    "paCaseID",
    "cancelReasonCode",
    "isPatientNotified",
    "paNote"
})
public class PACancelRequestStructure {

    @XmlElement(name = "PACaseID", required = true)
    protected String paCaseID;
    @XmlElement(name = "CancelReasonCode")
    @XmlSchemaType(name = "string")
    protected ReasonCode13 cancelReasonCode;
    @XmlElement(name = "IsPatientNotified")
    @XmlSchemaType(name = "string")
    protected BooleanCode isPatientNotified;
    @XmlElement(name = "PANote")
    protected String paNote;

    /**
     * Gets the value of the paCaseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACaseID() {
        return paCaseID;
    }

    /**
     * Sets the value of the paCaseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACaseID(String value) {
        this.paCaseID = value;
    }

    /**
     * Gets the value of the cancelReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link ReasonCode13 }
     *     
     */
    public ReasonCode13 getCancelReasonCode() {
        return cancelReasonCode;
    }

    /**
     * Sets the value of the cancelReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReasonCode13 }
     *     
     */
    public void setCancelReasonCode(ReasonCode13 value) {
        this.cancelReasonCode = value;
    }

    /**
     * Gets the value of the isPatientNotified property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanCode }
     *     
     */
    public BooleanCode getIsPatientNotified() {
        return isPatientNotified;
    }

    /**
     * Sets the value of the isPatientNotified property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanCode }
     *     
     */
    public void setIsPatientNotified(BooleanCode value) {
        this.isPatientNotified = value;
    }

    /**
     * Gets the value of the paNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPANote() {
        return paNote;
    }

    /**
     * Sets the value of the paNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPANote(String value) {
        this.paNote = value;
    }

}
