//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This transaction is a request from the prescriber to the payer to cancel a PARequest.
 * 
 * <p>Java class for PACancelRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PACancelRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{}PARequestAbstract">
 *       &lt;sequence>
 *         &lt;element name="Request" type="{}PACancelRequestStructure"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PACancelRequest", propOrder = {
    "request"
})
public class PACancelRequest
    extends PARequestAbstract
{

    @XmlElement(name = "Request", required = true)
    protected PACancelRequestStructure request;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link PACancelRequestStructure }
     *     
     */
    public PACancelRequestStructure getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link PACancelRequestStructure }
     *     
     */
    public void setRequest(PACancelRequestStructure value) {
        this.request = value;
    }

}
