//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PACancelResponseChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PACancelResponseChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Approved" type="{}PAApprovedForCancel"/>
 *         &lt;element name="Denied" type="{}PADeniedForCancelType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PACancelResponseChoiceType", propOrder = {
    "approved",
    "denied"
})
public class PACancelResponseChoiceType {

    @XmlElement(name = "Approved")
    protected PAApprovedForCancel approved;
    @XmlElement(name = "Denied")
    protected PADeniedForCancelType denied;

    /**
     * Gets the value of the approved property.
     * 
     * @return
     *     possible object is
     *     {@link PAApprovedForCancel }
     *     
     */
    public PAApprovedForCancel getApproved() {
        return approved;
    }

    /**
     * Sets the value of the approved property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAApprovedForCancel }
     *     
     */
    public void setApproved(PAApprovedForCancel value) {
        this.approved = value;
    }

    /**
     * Gets the value of the denied property.
     * 
     * @return
     *     possible object is
     *     {@link PADeniedForCancelType }
     *     
     */
    public PADeniedForCancelType getDenied() {
        return denied;
    }

    /**
     * Sets the value of the denied property.
     * 
     * @param value
     *     allowed object is
     *     {@link PADeniedForCancelType }
     *     
     */
    public void setDenied(PADeniedForCancelType value) {
        this.denied = value;
    }

}
