//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PACommon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PACommon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestReferenceNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="PAReferenceID" type="{}an1..35"/>
 *         &lt;element name="PAPriorityIndicator" type="{}PAPriorityIndicator" minOccurs="0"/>
 *         &lt;element name="BenefitsCoordination" type="{}BenefitsCoordinationRestricted" maxOccurs="4" minOccurs="0"/>
 *         &lt;element name="Patient" type="{}PatientMandatoryAddressType"/>
 *         &lt;element name="Pharmacy" type="{}MandatoryPharmacy" minOccurs="0"/>
 *         &lt;element name="Prescriber" type="{}MandatoryPrescriberChoice"/>
 *         &lt;element name="MedicationPrescribed" type="{}PAandREMsPrescribedMedication"/>
 *         &lt;element name="Facility" type="{}Facility" minOccurs="0"/>
 *         &lt;element name="Supervisor" type="{}SupervisorOptionalType" minOccurs="0"/>
 *         &lt;element name="Provider" type="{}Provider" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PACommon", propOrder = {
    "requestReferenceNumber",
    "paReferenceID",
    "paPriorityIndicator",
    "benefitsCoordination",
    "patient",
    "pharmacy",
    "prescriber",
    "medicationPrescribed",
    "facility",
    "supervisor",
    "provider"
})
@XmlSeeAlso({
    PARequestAbstract.class,
    PAResponseAbstract.class
})
public abstract class PACommon {

    @XmlElement(name = "RequestReferenceNumber")
    protected String requestReferenceNumber;
    @XmlElement(name = "PAReferenceID", required = true)
    protected String paReferenceID;
    @XmlElement(name = "PAPriorityIndicator")
    @XmlSchemaType(name = "string")
    protected PAPriorityIndicator paPriorityIndicator;
    @XmlElement(name = "BenefitsCoordination")
    protected List<BenefitsCoordinationRestricted> benefitsCoordination;
    @XmlElement(name = "Patient", required = true)
    protected PatientMandatoryAddressType patient;
    @XmlElement(name = "Pharmacy")
    protected MandatoryPharmacy pharmacy;
    @XmlElement(name = "Prescriber", required = true)
    protected MandatoryPrescriberChoice prescriber;
    @XmlElement(name = "MedicationPrescribed", required = true)
    protected PAandREMsPrescribedMedication medicationPrescribed;
    @XmlElement(name = "Facility")
    protected Facility facility;
    @XmlElement(name = "Supervisor")
    protected SupervisorOptionalType supervisor;
    @XmlElement(name = "Provider")
    protected Provider provider;

    /**
     * Gets the value of the requestReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestReferenceNumber() {
        return requestReferenceNumber;
    }

    /**
     * Sets the value of the requestReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestReferenceNumber(String value) {
        this.requestReferenceNumber = value;
    }

    /**
     * Gets the value of the paReferenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAReferenceID() {
        return paReferenceID;
    }

    /**
     * Sets the value of the paReferenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAReferenceID(String value) {
        this.paReferenceID = value;
    }

    /**
     * Gets the value of the paPriorityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link PAPriorityIndicator }
     *     
     */
    public PAPriorityIndicator getPAPriorityIndicator() {
        return paPriorityIndicator;
    }

    /**
     * Sets the value of the paPriorityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAPriorityIndicator }
     *     
     */
    public void setPAPriorityIndicator(PAPriorityIndicator value) {
        this.paPriorityIndicator = value;
    }

    /**
     * Gets the value of the benefitsCoordination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the benefitsCoordination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBenefitsCoordination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BenefitsCoordinationRestricted }
     * 
     * 
     */
    public List<BenefitsCoordinationRestricted> getBenefitsCoordination() {
        if (benefitsCoordination == null) {
            benefitsCoordination = new ArrayList<BenefitsCoordinationRestricted>();
        }
        return this.benefitsCoordination;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link PatientMandatoryAddressType }
     *     
     */
    public PatientMandatoryAddressType getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientMandatoryAddressType }
     *     
     */
    public void setPatient(PatientMandatoryAddressType value) {
        this.patient = value;
    }

    /**
     * Gets the value of the pharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link MandatoryPharmacy }
     *     
     */
    public MandatoryPharmacy getPharmacy() {
        return pharmacy;
    }

    /**
     * Sets the value of the pharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatoryPharmacy }
     *     
     */
    public void setPharmacy(MandatoryPharmacy value) {
        this.pharmacy = value;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * @return
     *     possible object is
     *     {@link MandatoryPrescriberChoice }
     *     
     */
    public MandatoryPrescriberChoice getPrescriber() {
        return prescriber;
    }

    /**
     * Sets the value of the prescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatoryPrescriberChoice }
     *     
     */
    public void setPrescriber(MandatoryPrescriberChoice value) {
        this.prescriber = value;
    }

    /**
     * Gets the value of the medicationPrescribed property.
     * 
     * @return
     *     possible object is
     *     {@link PAandREMsPrescribedMedication }
     *     
     */
    public PAandREMsPrescribedMedication getMedicationPrescribed() {
        return medicationPrescribed;
    }

    /**
     * Sets the value of the medicationPrescribed property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAandREMsPrescribedMedication }
     *     
     */
    public void setMedicationPrescribed(PAandREMsPrescribedMedication value) {
        this.medicationPrescribed = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link Facility }
     *     
     */
    public Facility getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Facility }
     *     
     */
    public void setFacility(Facility value) {
        this.facility = value;
    }

    /**
     * Gets the value of the supervisor property.
     * 
     * @return
     *     possible object is
     *     {@link SupervisorOptionalType }
     *     
     */
    public SupervisorOptionalType getSupervisor() {
        return supervisor;
    }

    /**
     * Sets the value of the supervisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupervisorOptionalType }
     *     
     */
    public void setSupervisor(SupervisorOptionalType value) {
        this.supervisor = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link Provider }
     *     
     */
    public Provider getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Provider }
     *     
     */
    public void setProvider(Provider value) {
        this.provider = value;
    }

}
