//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PADaysSupplyDosePerDay complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PADaysSupplyDosePerDay">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PADaysSupply" type="{}PADaysSupply"/>
 *         &lt;element name="PADosesPerDay" type="{}PADosesPerDay"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PADaysSupplyDosePerDay", propOrder = {
    "paDaysSupply",
    "paDosesPerDay"
})
public class PADaysSupplyDosePerDay {

    @XmlElement(name = "PADaysSupply", required = true)
    protected PADaysSupply paDaysSupply;
    @XmlElement(name = "PADosesPerDay", required = true)
    protected PADosesPerDay paDosesPerDay;

    /**
     * Gets the value of the paDaysSupply property.
     * 
     * @return
     *     possible object is
     *     {@link PADaysSupply }
     *     
     */
    public PADaysSupply getPADaysSupply() {
        return paDaysSupply;
    }

    /**
     * Sets the value of the paDaysSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link PADaysSupply }
     *     
     */
    public void setPADaysSupply(PADaysSupply value) {
        this.paDaysSupply = value;
    }

    /**
     * Gets the value of the paDosesPerDay property.
     * 
     * @return
     *     possible object is
     *     {@link PADosesPerDay }
     *     
     */
    public PADosesPerDay getPADosesPerDay() {
        return paDosesPerDay;
    }

    /**
     * Sets the value of the paDosesPerDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link PADosesPerDay }
     *     
     */
    public void setPADosesPerDay(PADosesPerDay value) {
        this.paDosesPerDay = value;
    }

}
