//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PADeniedForCancelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PADeniedForCancelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReasonCode" type="{}ReasonCode12" minOccurs="0"/>
 *         &lt;element name="PANote" type="{}an1..2000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PADeniedForCancelType", propOrder = {
    "reasonCode",
    "paNote"
})
public class PADeniedForCancelType {

    @XmlElement(name = "ReasonCode")
    @XmlSchemaType(name = "string")
    protected ReasonCode12 reasonCode;
    @XmlElement(name = "PANote")
    protected String paNote;

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link ReasonCode12 }
     *     
     */
    public ReasonCode12 getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReasonCode12 }
     *     
     */
    public void setReasonCode(ReasonCode12 value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the paNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPANote() {
        return paNote;
    }

    /**
     * Sets the value of the paNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPANote(String value) {
        this.paNote = value;
    }

}
