//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PAPriorityIndicator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PAPriorityIndicator">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="X"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PAPriorityIndicator")
@XmlEnum
public enum PAPriorityIndicator {


    /**
     * Standard Priority - A request with standard time-frames is one that the physician/prescriber has deemed to not be life threatening or would otherwise not endanger the well-being of the patient if the request is not handled with immediacy. These requests are treated as secondary to urgent requests. (note: CMS guidance is 72 hours)
     * 
     */
    S,

    /**
     * Urgent / Expedited Priority- A request designation is when the treatment requested is required to prevent serious deterioration in the member’s health or could jeopardize the enrollee’s ability to regain maximum function. (note: CMS guidance is 24 hours)
     * 
     */
    X;

    public String value() {
        return name();
    }

    public static PAPriorityIndicator fromValue(String v) {
        return valueOf(v);
    }

}
