//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PAResponseChoiceTypeForAppeal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PAResponseChoiceTypeForAppeal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Approved" type="{}PAApprovedDetailForAppeal"/>
 *         &lt;element name="Denied" type="{}PADeniedTypeForAppeal"/>
 *         &lt;element name="Open" type="{}PAOpenTypeResponseForAppeal"/>
 *         &lt;element name="Closed" type="{}PAReasonClosedCodeTypeForAppeal"/>
 *         &lt;element name="PartiallyDenied" type="{}PAApprovedDetailForAppeal"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PAResponseChoiceTypeForAppeal", propOrder = {
    "approved",
    "denied",
    "open",
    "closed",
    "partiallyDenied"
})
public class PAResponseChoiceTypeForAppeal {

    @XmlElement(name = "Approved")
    protected PAApprovedDetailForAppeal approved;
    @XmlElement(name = "Denied")
    protected PADeniedTypeForAppeal denied;
    @XmlElement(name = "Open")
    protected PAOpenTypeResponseForAppeal open;
    @XmlElement(name = "Closed")
    protected PAReasonClosedCodeTypeForAppeal closed;
    @XmlElement(name = "PartiallyDenied")
    protected PAApprovedDetailForAppeal partiallyDenied;

    /**
     * Gets the value of the approved property.
     * 
     * @return
     *     possible object is
     *     {@link PAApprovedDetailForAppeal }
     *     
     */
    public PAApprovedDetailForAppeal getApproved() {
        return approved;
    }

    /**
     * Sets the value of the approved property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAApprovedDetailForAppeal }
     *     
     */
    public void setApproved(PAApprovedDetailForAppeal value) {
        this.approved = value;
    }

    /**
     * Gets the value of the denied property.
     * 
     * @return
     *     possible object is
     *     {@link PADeniedTypeForAppeal }
     *     
     */
    public PADeniedTypeForAppeal getDenied() {
        return denied;
    }

    /**
     * Sets the value of the denied property.
     * 
     * @param value
     *     allowed object is
     *     {@link PADeniedTypeForAppeal }
     *     
     */
    public void setDenied(PADeniedTypeForAppeal value) {
        this.denied = value;
    }

    /**
     * Gets the value of the open property.
     * 
     * @return
     *     possible object is
     *     {@link PAOpenTypeResponseForAppeal }
     *     
     */
    public PAOpenTypeResponseForAppeal getOpen() {
        return open;
    }

    /**
     * Sets the value of the open property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAOpenTypeResponseForAppeal }
     *     
     */
    public void setOpen(PAOpenTypeResponseForAppeal value) {
        this.open = value;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link PAReasonClosedCodeTypeForAppeal }
     *     
     */
    public PAReasonClosedCodeTypeForAppeal getClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAReasonClosedCodeTypeForAppeal }
     *     
     */
    public void setClosed(PAReasonClosedCodeTypeForAppeal value) {
        this.closed = value;
    }

    /**
     * Gets the value of the partiallyDenied property.
     * 
     * @return
     *     possible object is
     *     {@link PAApprovedDetailForAppeal }
     *     
     */
    public PAApprovedDetailForAppeal getPartiallyDenied() {
        return partiallyDenied;
    }

    /**
     * Sets the value of the partiallyDenied property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAApprovedDetailForAppeal }
     *     
     */
    public void setPartiallyDenied(PAApprovedDetailForAppeal value) {
        this.partiallyDenied = value;
    }

}
