//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatientFullAbstract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientFullAbstract">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identification" type="{}PatientID" minOccurs="0"/>
 *         &lt;element name="Name" type="{}NameType"/>
 *         &lt;element name="FormerName" type="{}NameType" minOccurs="0"/>
 *         &lt;element name="Gender" type="{}Gender"/>
 *         &lt;element name="DateOfBirth" type="{}DateType"/>
 *         &lt;element name="Address" type="{}AddressType" minOccurs="0"/>
 *         &lt;element name="CommunicationNumbers" type="{}CommunicationNumbersType" minOccurs="0"/>
 *         &lt;element name="PatientLocation" type="{}PatientLocation" minOccurs="0"/>
 *         &lt;element name="LanguageNameCode" type="{}an1..3" minOccurs="0"/>
 *         &lt;element name="ResidenceCode" type="{}ResidenceCode" minOccurs="0"/>
 *         &lt;element name="PregnancyIndicator" type="{}BooleanCode" minOccurs="0"/>
 *         &lt;element name="Race" type="{}CDCCode" minOccurs="0"/>
 *         &lt;element name="Ethnicity" type="{}CDCCode" minOccurs="0"/>
 *         &lt;element name="SubstanceUse" type="{}SubstanceUseType" minOccurs="0"/>
 *         &lt;element name="AlternateContact" type="{}AlternateContactStructure" minOccurs="0"/>
 *         &lt;element name="GestationalAge" type="{}n1..2" minOccurs="0"/>
 *         &lt;element name="HospiceIndicator" type="{}HospiceIndicator" minOccurs="0"/>
 *         &lt;element name="FinancialGuarantor" type="{}FinancialGuarantorType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientFullAbstract", propOrder = {
    "identification",
    "name",
    "formerName",
    "gender",
    "dateOfBirth",
    "address",
    "communicationNumbers",
    "patientLocation",
    "languageNameCode",
    "residenceCode",
    "pregnancyIndicator",
    "race",
    "ethnicity",
    "substanceUse",
    "alternateContact",
    "gestationalAge",
    "hospiceIndicator",
    "financialGuarantor"
})
@XmlSeeAlso({
    PatientWithSubstanceUseForCensus.class,
    CFPatient.class,
    PatientFull.class,
    PatientWithSubstanceUse.class,
    PatientMandatoryAddressForNewRx.class,
    CFPatientWithSubstanceUse.class,
    PatientFullWithSubstanceUse.class,
    Patient.class
})
public class PatientFullAbstract {

    @XmlElement(name = "Identification")
    protected PatientID identification;
    @XmlElement(name = "Name", required = true)
    protected NameType name;
    @XmlElement(name = "FormerName")
    protected NameType formerName;
    @XmlElement(name = "Gender", required = true)
    @XmlSchemaType(name = "string")
    protected Gender gender;
    @XmlElement(name = "DateOfBirth", required = true)
    protected DateType dateOfBirth;
    @XmlElement(name = "Address")
    protected AddressType address;
    @XmlElement(name = "CommunicationNumbers")
    protected CommunicationNumbersType communicationNumbers;
    @XmlElement(name = "PatientLocation")
    protected PatientLocation patientLocation;
    @XmlElement(name = "LanguageNameCode")
    protected String languageNameCode;
    @XmlElement(name = "ResidenceCode")
    protected String residenceCode;
    @XmlElement(name = "PregnancyIndicator")
    @XmlSchemaType(name = "string")
    protected BooleanCode pregnancyIndicator;
    @XmlElement(name = "Race")
    protected CDCCode race;
    @XmlElement(name = "Ethnicity")
    protected CDCCode ethnicity;
    @XmlElement(name = "SubstanceUse")
    protected SubstanceUseType substanceUse;
    @XmlElement(name = "AlternateContact")
    protected AlternateContactStructure alternateContact;
    @XmlElement(name = "GestationalAge")
    protected String gestationalAge;
    @XmlElement(name = "HospiceIndicator")
    protected String hospiceIndicator;
    @XmlElement(name = "FinancialGuarantor")
    protected FinancialGuarantorType financialGuarantor;

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link PatientID }
     *     
     */
    public PatientID getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientID }
     *     
     */
    public void setIdentification(PatientID value) {
        this.identification = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setName(NameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the formerName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getFormerName() {
        return formerName;
    }

    /**
     * Sets the value of the formerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setFormerName(NameType value) {
        this.formerName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDateOfBirth(DateType value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the communicationNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationNumbersType }
     *     
     */
    public CommunicationNumbersType getCommunicationNumbers() {
        return communicationNumbers;
    }

    /**
     * Sets the value of the communicationNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationNumbersType }
     *     
     */
    public void setCommunicationNumbers(CommunicationNumbersType value) {
        this.communicationNumbers = value;
    }

    /**
     * Gets the value of the patientLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PatientLocation }
     *     
     */
    public PatientLocation getPatientLocation() {
        return patientLocation;
    }

    /**
     * Sets the value of the patientLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientLocation }
     *     
     */
    public void setPatientLocation(PatientLocation value) {
        this.patientLocation = value;
    }

    /**
     * Gets the value of the languageNameCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageNameCode() {
        return languageNameCode;
    }

    /**
     * Sets the value of the languageNameCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageNameCode(String value) {
        this.languageNameCode = value;
    }

    /**
     * Gets the value of the residenceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidenceCode() {
        return residenceCode;
    }

    /**
     * Sets the value of the residenceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidenceCode(String value) {
        this.residenceCode = value;
    }

    /**
     * Gets the value of the pregnancyIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanCode }
     *     
     */
    public BooleanCode getPregnancyIndicator() {
        return pregnancyIndicator;
    }

    /**
     * Sets the value of the pregnancyIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanCode }
     *     
     */
    public void setPregnancyIndicator(BooleanCode value) {
        this.pregnancyIndicator = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link CDCCode }
     *     
     */
    public CDCCode getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCCode }
     *     
     */
    public void setRace(CDCCode value) {
        this.race = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link CDCCode }
     *     
     */
    public CDCCode getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCCode }
     *     
     */
    public void setEthnicity(CDCCode value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the substanceUse property.
     * 
     * @return
     *     possible object is
     *     {@link SubstanceUseType }
     *     
     */
    public SubstanceUseType getSubstanceUse() {
        return substanceUse;
    }

    /**
     * Sets the value of the substanceUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubstanceUseType }
     *     
     */
    public void setSubstanceUse(SubstanceUseType value) {
        this.substanceUse = value;
    }

    /**
     * Gets the value of the alternateContact property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateContactStructure }
     *     
     */
    public AlternateContactStructure getAlternateContact() {
        return alternateContact;
    }

    /**
     * Sets the value of the alternateContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateContactStructure }
     *     
     */
    public void setAlternateContact(AlternateContactStructure value) {
        this.alternateContact = value;
    }

    /**
     * Gets the value of the gestationalAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGestationalAge() {
        return gestationalAge;
    }

    /**
     * Sets the value of the gestationalAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGestationalAge(String value) {
        this.gestationalAge = value;
    }

    /**
     * Gets the value of the hospiceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHospiceIndicator() {
        return hospiceIndicator;
    }

    /**
     * Sets the value of the hospiceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHospiceIndicator(String value) {
        this.hospiceIndicator = value;
    }

    /**
     * Gets the value of the financialGuarantor property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialGuarantorType }
     *     
     */
    public FinancialGuarantorType getFinancialGuarantor() {
        return financialGuarantor;
    }

    /**
     * Sets the value of the financialGuarantor property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialGuarantorType }
     *     
     */
    public void setFinancialGuarantor(FinancialGuarantorType value) {
        this.financialGuarantor = value;
    }

}
