//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatientCodifiedNoteQualifier.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PatientCodifiedNoteQualifier">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AA"/>
 *     &lt;enumeration value="AB"/>
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="AD"/>
 *     &lt;enumeration value="AE"/>
 *     &lt;enumeration value="AF"/>
 *     &lt;enumeration value="AG"/>
 *     &lt;enumeration value="AH"/>
 *     &lt;enumeration value="AJ"/>
 *     &lt;enumeration value="AK"/>
 *     &lt;enumeration value="AL"/>
 *     &lt;enumeration value="AM"/>
 *     &lt;enumeration value="AN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PatientCodifiedNoteQualifier")
@XmlEnum
public enum PatientCodifiedNoteQualifier {


    /**
     * Dose(s) administered from Emergency box (kit) or automated dispensing machine.
     * 
     */
    AA,

    /**
     * Product has been contaminated during administration.
     * 
     */
    AB,

    /**
     * Patient requires oral solid medications to be crushed before administration.
     * 
     */
    AC,

    /**
     * Patient requests/requires oral solid medications to be smallest tablet/capsule.
     * 
     */
    AD,

    /**
     * Medications administered via gastric tube. Used only if Route of Administration is not specified as gastric tube.
     * 
     */
    AE,

    /**
     * Patient requests product to be dispensed as written.
     * 
     */
    AF,

    /**
     * Compound requested – allergy to inactive ingredient found in commercially available product. To be used when product is commercially available.
     * 
     */
    AG,

    /**
     * Compound requested – dosage form not commercially available. To be used when product is commercially available. To be used when product is commercially available.
     * 
     */
    AH,

    /**
     * Compound requested – strength not commercially available. To be used when product is commercially available.
     * 
     */
    AJ,

    /**
     * Incremental Dispensing – prescriber allows pharmacy to dispense in quantities less than the prescribed quantity. To be used when the prescriber allows the pharmacy to dispense in quantities less than total prescribed quantity.
     * 
     */
    AK,

    /**
     * Patient needs labs, appointment, or office visit. To be used when patient needs to schedule an office or laboratory appointment.
     * 
     */
    AL,

    /**
     * Patient bringing drug coupon, discount, or other benefit card.
     * 
     */
    AM,

    /**
     * This prescription is a mail-order, vacation, lost, stolen, or replacement supply. To be used when prescription is in response to a mail-order bridge supply; vacation supply, lost, or stolen supply; or miscellaneous replacement supply.
     * 
     */
    AN;

    public String value() {
        return name();
    }

    public static PatientCodifiedNoteQualifier fromValue(String v) {
        return valueOf(v);
    }

}
