//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayerResponsibilityCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PayerResponsibilityCode">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="PP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PayerResponsibilityCode")
@XmlEnum
public enum PayerResponsibilityCode {


    /**
     * Primary
     * 
     */
    P,

    /**
     * Secondary
     * 
     */
    S,

    /**
     * Tertiary
     * 
     */
    T,

    /**
     * Unknown
     * 
     */
    U,

    /**
     * Private Pay
     * 
     */
    PP;

    public String value() {
        return name();
    }

    public static PayerResponsibilityCode fromValue(String v) {
        return valueOf(v);
    }

}
