//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Value P2
 * 
 * <p>Java class for Pharmacy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pharmacy">
 *   &lt;complexContent>
 *     &lt;restriction base="{}OptionalPharmacy">
 *       &lt;sequence>
 *         &lt;element name="Identification" type="{}PharmacyID"/>
 *         &lt;element name="Specialty" type="{}an1..10" minOccurs="0"/>
 *         &lt;element name="Pharmacist" type="{}Pharmacist" minOccurs="0"/>
 *         &lt;element name="BusinessName" type="{}an1..70"/>
 *         &lt;element name="Address" type="{}AddressType" minOccurs="0"/>
 *         &lt;element name="CommunicationNumbers" type="{}CommunicationNumbersType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pharmacy")
@XmlSeeAlso({
    MandatoryPharmacy.class
})
public class Pharmacy
    extends OptionalPharmacy
{


}
