//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriorAuthorizationStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PriorAuthorizationStatus">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="R"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PriorAuthorizationStatus")
@XmlEnum
public enum PriorAuthorizationStatus {


    /**
     * Approved - The medication was approved by the payer
     * 
     */
    A,

    /**
     * Denied - The medication was not approved by the payer.
     * 
     */
    D,

    /**
     * Deferred - The medication request being reviewed by the payer.
     * 
     */
    F,

    /**
     * Not Required - A prior authorization is not required for this medication.
     * 
     */
    N,

    /**
     * Requested - The action of obtaining a prior authorization approval is being sought.
     * 
     */
    R;

    public String value() {
        return name();
    }

    public static PriorAuthorizationStatus fromValue(String v) {
        return valueOf(v);
    }

}
