//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductQualifierCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProductQualifierCode">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="DI"/>
 *     &lt;enumeration value="ND"/>
 *     &lt;enumeration value="RT"/>
 *     &lt;enumeration value="UN"/>
 *     &lt;enumeration value="UP"/>
 *     &lt;enumeration value="NH"/>
 *     &lt;enumeration value="GMP"/>
 *     &lt;enumeration value="GPI"/>
 *     &lt;enumeration value="GSP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProductQualifierCode")
@XmlEnum
public enum ProductQualifierCode {


    /**
     * Device Identifier
     * 
     */
    DI,

    /**
     * National Drug Code (NDC)
     * 
     */
    ND,

    /**
     * National Drug File Reference (NDF-RT)
     * 
     */
    RT,

    /**
     * Unique Ingredient Identifier (UNII)
     * 
     */
    UN,

    /**
     * Universal Product Code (UPC)
     * 
     */
    UP,

    /**
     * Health Related Item (HRI)
     * 
     */
    NH,

    /**
     * Gold Standard Marketed Product Identifier (MPid) 
     * 
     */
    GMP,

    /**
     * Gold Standard Product Identifier (ProdID)
     * 
     */
    GPI,

    /**
     * Gold Standard Specific Product Identifier (SPID)
     * 
     */
    GSP;

    public String value() {
        return name();
    }

    public static ProductQualifierCode fromValue(String v) {
        return valueOf(v);
    }

}
