//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuestionDetailCommonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuestionDetailCommonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QuestionID" type="{}an1..35"/>
 *         &lt;element name="SequenceNumber" type="{}n1..3"/>
 *         &lt;element name="QuestionLevel" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="QuestionText" type="{}an1..2000"/>
 *         &lt;element name="CodedReference" type="{}CodedReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DefaultNextQuestionID" type="{}an1..35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuestionDetailCommonType", propOrder = {
    "questionID",
    "sequenceNumber",
    "questionLevel",
    "questionText",
    "codedReference",
    "defaultNextQuestionID"
})
@XmlSeeAlso({
    QuestionDetailForResponseType.class,
    QuestionDetailForRequestType.class
})
public class QuestionDetailCommonType {

    @XmlElement(name = "QuestionID", required = true)
    protected String questionID;
    @XmlElement(name = "SequenceNumber", required = true)
    protected String sequenceNumber;
    @XmlElement(name = "QuestionLevel")
    protected String questionLevel;
    @XmlElement(name = "QuestionText", required = true)
    protected String questionText;
    @XmlElement(name = "CodedReference")
    protected List<CodedReference> codedReference;
    @XmlElement(name = "DefaultNextQuestionID")
    protected String defaultNextQuestionID;

    /**
     * Gets the value of the questionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionID() {
        return questionID;
    }

    /**
     * Sets the value of the questionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionID(String value) {
        this.questionID = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceNumber(String value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the questionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionLevel() {
        return questionLevel;
    }

    /**
     * Sets the value of the questionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionLevel(String value) {
        this.questionLevel = value;
    }

    /**
     * Gets the value of the questionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionText() {
        return questionText;
    }

    /**
     * Sets the value of the questionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionText(String value) {
        this.questionText = value;
    }

    /**
     * Gets the value of the codedReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codedReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodedReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedReference }
     * 
     * 
     */
    public List<CodedReference> getCodedReference() {
        if (codedReference == null) {
            codedReference = new ArrayList<CodedReference>();
        }
        return this.codedReference;
    }

    /**
     * Gets the value of the defaultNextQuestionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultNextQuestionID() {
        return defaultNextQuestionID;
    }

    /**
     * Sets the value of the defaultNextQuestionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultNextQuestionID(String value) {
        this.defaultNextQuestionID = value;
    }

}
