//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonCode20.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReasonCode20">
 *   &lt;restriction base="{}ReasonCode">
 *     &lt;enumeration value="BX"/>
 *     &lt;enumeration value="BY"/>
 *     &lt;enumeration value="CD"/>
 *     &lt;enumeration value="CJ"/>
 *     &lt;enumeration value="CK"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="CN"/>
 *     &lt;enumeration value="DN"/>
 *     &lt;enumeration value="DO"/>
 *     &lt;enumeration value="DP"/>
 *     &lt;enumeration value="DQ"/>
 *     &lt;enumeration value="DR"/>
 *     &lt;enumeration value="DS"/>
 *     &lt;enumeration value="DT"/>
 *     &lt;enumeration value="DU"/>
 *     &lt;enumeration value="DV"/>
 *     &lt;enumeration value="DW"/>
 *     &lt;enumeration value="DX"/>
 *     &lt;enumeration value="DY"/>
 *     &lt;enumeration value="DZ"/>
 *     &lt;enumeration value="EA"/>
 *     &lt;enumeration value="EB"/>
 *     &lt;enumeration value="EC"/>
 *     &lt;enumeration value="ED"/>
 *     &lt;enumeration value="EE"/>
 *     &lt;enumeration value="EF"/>
 *     &lt;enumeration value="EG"/>
 *     &lt;enumeration value="EH"/>
 *     &lt;enumeration value="EI"/>
 *     &lt;enumeration value="EJ"/>
 *     &lt;enumeration value="EK"/>
 *     &lt;enumeration value="EL"/>
 *     &lt;enumeration value="EM"/>
 *     &lt;enumeration value="EN"/>
 *     &lt;enumeration value="EO"/>
 *     &lt;enumeration value="EP"/>
 *     &lt;enumeration value="EQ"/>
 *     &lt;enumeration value="ER"/>
 *     &lt;enumeration value="ES"/>
 *     &lt;enumeration value="ET"/>
 *     &lt;enumeration value="EU"/>
 *     &lt;enumeration value="EV"/>
 *     &lt;enumeration value="EW"/>
 *     &lt;enumeration value="EX"/>
 *     &lt;enumeration value="EY"/>
 *     &lt;enumeration value="EZ"/>
 *     &lt;enumeration value="FA"/>
 *     &lt;enumeration value="FB"/>
 *     &lt;enumeration value="FC"/>
 *     &lt;enumeration value="FD"/>
 *     &lt;enumeration value="FE"/>
 *     &lt;enumeration value="FF"/>
 *     &lt;enumeration value="FG"/>
 *     &lt;enumeration value="FH"/>
 *     &lt;enumeration value="FI"/>
 *     &lt;enumeration value="FJ"/>
 *     &lt;enumeration value="FK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReasonCode20")
@XmlEnum(ReasonCode.class)
public enum ReasonCode20 {


    /**
     * Electronic Prior Authorization not supported. Submit via other methods.
     * 
     */
    BX,

    /**
     * Other
     * 
     */
    BY,

    /**
     * Cannot find matching patient
     * 
     */
    CD,

    /**
     * Closed by Provider
     * 
     */
    CJ,

    /**
     * Closed by Member
     * 
     */
    CK,

    /**
     * Attachment type (mimetype) not supported
     * 
     */
    CL,

    /**
     * Response content is inconsistent with the question
     * 
     */
    CN,

    /**
     * Excessive days supply according to REMS restrictions.
     * 
     */
    DN,

    /**
     * Insufficient days supply according to REMS restrictions.
     * 
     */
    DO,

    /**
     * Inappropriate days supply for the quantity prescribed according to REMS restrictions.
     * 
     */
    DP,

    /**
     * Excessive dosage according to REMS restrictions.
     * 
     */
    DQ,

    /**
     * Insufficient dosage according to REMS restrictions.
     * 
     */
    DR,

    /**
     * Refills not permitted according to REMS restrictions.
     * 
     */
    DS,

    /**
     * Quantity limit exceeds maximum according to REMS restrictions.
     * 
     */
    DT,

    /**
     * Inappropriate quantity prescribed according to REMS restrictions.
     * 
     */
    DU,

    /**
     * Laboratory test results not documented
     * 
     */
    DV,

    /**
     * Laboratory test not conducted within specified time period.
     * 
     */
    DW,

    /**
     * Prescribing not authorized due to laboratory test results.
     * 
     */
    DX,

    /**
     * Prescriber has not documented safe use conditions.
     * 
     */
    DY,

    /**
     * Prescriber has not documented patient opioid tolerance.
     * 
     */
    DZ,

    /**
     * Prescriber has not documented that patient has met contraceptive requirements.
     * 
     */
    EA,

    /**
     * Invalid prescription may not be electronically submitted; hand written orders only.
     * 
     */
    EB,

    /**
     * Non matched Diagnosis code submitted.
     * 
     */
    EC,

    /**
     * Patient First Name must be submitted.
     * 
     */
    ED,

    /**
     * Patient Last Name must  be submitted.
     * 
     */
    EE,

    /**
     * Patient Zip Code must be submitted.
     * 
     */
    EF,

    /**
     * Multiple patient matches; call REMS Administrator.
     * 
     */
    EG,

    /**
     * Patient First Name must be submitted.
     * 
     */
    EH,

    /**
     * Patient is younger than the minimum age required.
     * 
     */
    EI,

    /**
     * Patient is older than the maximum age allowed.
     * 
     */
    EJ,

    /**
     * Patient is on a "Do Not Rechallenge List".
     * 
     */
    EK,

    /**
     * Patient has not documented safe use conditions.
     * 
     */
    EL,

    /**
     * Patient must enroll/certify.
     * 
     */
    EM,

    /**
     * Patient must re-enroll/re-certify.
     * 
     */
    EN,

    /**
     * Pharmacy not enrolled/certified.
     * 
     */
    EO,

    /**
     * Pharmacy must re-enroll/re-certify.
     * 
     */
    EP,

    /**
     * Pharmacy not matched.
     * 
     */
    EQ,

    /**
     * Invalid Pharmacy type - contact program administrator.
     * 
     */
    ER,

    /**
     * Presciber must enroll/certify.
     * 
     */
    ES,

    /**
     * Presciber must re-enroll/re-certify.
     * 
     */
    ET,

    /**
     * Prescriber qualifications for REMS not met.
     * 
     */
    EU,

    /**
     * Missing/Invalid Prescriber ID.
     * 
     */
    EV,

    /**
     * Non-Matched Prescriber last name.
     * 
     */
    EW,

    /**
     * Prescriber has been deactivated.
     * 
     */
    EX,

    /**
     * Pharmacy is not participating.
     * 
     */
    EY,

    /**
     * Prescriber-Patient Agreement not found.
     * 
     */
    EZ,

    /**
     * No attempt will be made to obtain REMS approval.
     * 
     */
    FA,

    /**
     * Electronic REMS not supported. Submit via other methods.
     * 
     */
    FB,

    /**
     * Can not find REMSCaseID
     * 
     */
    FC,

    /**
     * REMS Authorization not required for patient/medication.
     * 
     */
    FD,

    /**
     * Patient not eligible
     * 
     */
    FE,

    /**
     * REMS Authorization duplicate/approved
     * 
     */
    FF,

    /**
     * REMS Authorization duplicate/in process
     * 
     */
    FG,

    /**
     * REMS Authorization duplicate/denied
     * 
     */
    FH,

    /**
     * Closed by REMS Administrator
     * 
     */
    FI,

    /**
     * The receiver is not the REMS Administrator for this patient
     * 
     */
    FJ,

    /**
     * The receiver is not the REMS Administrator for this patient and medication combination
     * 
     */
    FK;

    public String value() {
        return name();
    }

    public static ReasonCode20 fromValue(String v) {
        return valueOf(v);
    }

}
