//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonCode5.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReasonCode5">
 *   &lt;restriction base="{}ReasonCode">
 *     &lt;enumeration value="AQ"/>
 *     &lt;enumeration value="DJ"/>
 *     &lt;enumeration value="DK"/>
 *     &lt;enumeration value="DL"/>
 *     &lt;enumeration value="DM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReasonCode5")
@XmlEnum(ReasonCode.class)
public enum ReasonCode5 {


    /**
     * More Medication History Available
     * 
     */
    AQ,

    /**
     * No Data – There is a response indicating that no data was found for the search criteria provided in the search request.
     * 
     */
    DJ,

    /**
     * Prescription Data
     * 
     */
    DK,

    /**
     * Disallowed – There was a permission problem of some type performing this request against this destination.
     * 
     */
    DL,

    /**
     * Error- This response indicates a processing error in performing this request. (May only be used when a more specific ReasonCode does not apply).
     * 
     */
    DM;

    public String value() {
        return name();
    }

    public static ReasonCode5 fromValue(String v) {
        return valueOf(v);
    }

}
