//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonCode2.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReasonCode2">
 *   &lt;restriction base="{}ReasonCode">
 *     &lt;enumeration value="AA"/>
 *     &lt;enumeration value="AB"/>
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="AE"/>
 *     &lt;enumeration value="AF"/>
 *     &lt;enumeration value="AL"/>
 *     &lt;enumeration value="AM"/>
 *     &lt;enumeration value="AN"/>
 *     &lt;enumeration value="AO"/>
 *     &lt;enumeration value="AP"/>
 *     &lt;enumeration value="BE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReasonCode2")
@XmlEnum(ReasonCode.class)
public enum ReasonCode2 {


    /**
     * Patient unknown to the Provider
     * 
     */
    AA,

    /**
     * Patient never under  Provider care
     * 
     */
    AB,

    /**
     * Patient no longer under  Provider care
     * 
     */
    AC,

    /**
     * Medication never prescribed for the patient
     * 
     */
    AE,

    /**
     * Patient should contact Provider first
     * 
     */
    AF,

    /**
     * Change not appropriate
     * 
     */
    AL,

    /**
     * Patient needs appointment
     * 
     */
    AM,

    /**
     * Prescriber not associated with this practice or location
     * 
     */
    AN,

    /**
     * No attempt will be made to obtain Prior Authorization
     * 
     */
    AO,

    /**
     * Request already responded to by other means (e.g. phone or fax)
     * 
     */
    AP,

    /**
     * Medication denied at patient request
     * 
     */
    BE;

    public String value() {
        return name();
    }

    public static ReasonCode2 fromValue(String v) {
        return valueOf(v);
    }

}
