//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonCode7.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReasonCode7">
 *   &lt;restriction base="{}ReasonCode">
 *     &lt;enumeration value="AA"/>
 *     &lt;enumeration value="AB"/>
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="AD"/>
 *     &lt;enumeration value="AG"/>
 *     &lt;enumeration value="AO"/>
 *     &lt;enumeration value="BF"/>
 *     &lt;enumeration value="BG"/>
 *     &lt;enumeration value="BP"/>
 *     &lt;enumeration value="BQ"/>
 *     &lt;enumeration value="BT"/>
 *     &lt;enumeration value="CS"/>
 *     &lt;enumeration value="DB"/>
 *     &lt;enumeration value="DC"/>
 *     &lt;enumeration value="DD"/>
 *     &lt;enumeration value="DE"/>
 *     &lt;enumeration value="FS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReasonCode7")
@XmlEnum(ReasonCode.class)
public enum ReasonCode7 {


    /**
     * Patient unknown to the Provider
     * 
     */
    AA,

    /**
     * Patient never under  Provider care
     * 
     */
    AB,

    /**
     * Patient no longer under  Provider care
     * 
     */
    AC,

    /**
     * Patient has requested refill too soon
     * 
     */
    AD,

    /**
     * Fill/Refill not appropriate
     * 
     */
    AG,

    /**
     * No attempt will be made to obtain Prior Authorization
     * 
     */
    AO,

    /**
     * Conscientious objection
     * 
     */
    BF,

    /**
     * Not the patient-desired pharmacy
     * 
     */
    BG,

    /**
     * Out of Stock/Manufacturer Back Order – NDC requested is currently on back order from the manufacturer.
     * 
     */
    BP,

    /**
     * Discontinued by Manufacturer – NDC requested has been discontinued by the manufacturer.
     * 
     */
    BQ,

    /**
     * Drug Recalled by Manufacturer – NDC requested has been recalled by the manufacturer.
     * 
     */
    BT,

    /**
     * Prescription not found
     * 
     */
    CS,

    /**
     * Drug Use Evaluation
     * 
     */
    DB,

    /**
     * No refills remaining or medication order has expired
     * 
     */
    DC,

    /**
     * Pharmacy has no intention to stock the medication requested/prescribed
     * 
     */
    DD,

    /**
     * Prior Authorization has been denied by payer
     * 
     */
    DE,

    /**
     * The medication prescribed is out of stock and cannot be obtained in a clinically appropriate timeframe.
     * 
     */
    FS;

    public String value() {
        return name();
    }

    public static ReasonCode7 fromValue(String v) {
        return valueOf(v);
    }

}
