//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonCode4.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReasonCode4">
 *   &lt;restriction base="{}ReasonCode">
 *     &lt;enumeration value="AP"/>
 *     &lt;enumeration value="AS"/>
 *     &lt;enumeration value="AT"/>
 *     &lt;enumeration value="AU"/>
 *     &lt;enumeration value="AV"/>
 *     &lt;enumeration value="AW"/>
 *     &lt;enumeration value="AX"/>
 *     &lt;enumeration value="AY"/>
 *     &lt;enumeration value="AZ"/>
 *     &lt;enumeration value="BA"/>
 *     &lt;enumeration value="BG"/>
 *     &lt;enumeration value="BY"/>
 *     &lt;enumeration value="CL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReasonCode4")
@XmlEnum(ReasonCode.class)
public enum ReasonCode4 {


    /**
     * Request already responded to by other means (e.g. phone or fax)
     * 
     */
    AP,

    /**
     * Qualified provider unavailable to provide this service
     * 
     */
    AS,

    /**
     * Not accepting new patients
     * 
     */
    AT,

    /**
     * Unable to accommodate service based parameters
     * 
     */
    AU,

    /**
     * These parameters do not meet the patient's needs
     * 
     */
    AV,

    /**
     * Based on assessment, patient needs are outside of contractual agreement
     * 
     */
    AW,

    /**
     * Patient condition no longer applicable
     * 
     */
    AX,

    /**
     * Patient not available for service
     * 
     */
    AY,

    /**
     * Patient declined service
     * 
     */
    AZ,

    /**
     * Qualified provider unavailable to provide this service
     * 
     */
    BA,

    /**
     * Not the patient-desired pharmacy
     * 
     */
    BG,

    /**
     * Other
     * 
     */
    BY,

    /**
     * Attachment type (mimetype) not supported
     * 
     */
    CL;

    public String value() {
        return name();
    }

    public static ReasonCode4 fromValue(String v) {
        return valueOf(v);
    }

}
