//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonCode17.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReasonCode17">
 *   &lt;restriction base="{}ReasonCode">
 *     &lt;enumeration value="AA"/>
 *     &lt;enumeration value="AF"/>
 *     &lt;enumeration value="AP"/>
 *     &lt;enumeration value="BC"/>
 *     &lt;enumeration value="BY"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="CD"/>
 *     &lt;enumeration value="CQ"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="CS"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="CU"/>
 *     &lt;enumeration value="CV"/>
 *     &lt;enumeration value="CW"/>
 *     &lt;enumeration value="CX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReasonCode17")
@XmlEnum(ReasonCode.class)
public enum ReasonCode17 {


    /**
     * Patient unknown to the Provider
     * 
     */
    AA,

    /**
     * Patient should contact Provider first
     * 
     */
    AF,

    /**
     * Request already responded to by other means (e.g. phone or fax)
     * 
     */
    AP,

    /**
     * Not Authorized to Release
     * 
     */
    BC,

    /**
     * Other
     * 
     */
    BY,

    /**
     * Unable to locate based on insufficient information - identifiers do not match
     * 
     */
    CA,

    /**
     * Cannot find matching patient
     * 
     */
    CD,

    /**
     * Transfer needs to be discussed - call with information provided
     * 
     */
    CQ,

    /**
     * Prescription(s) cannot be electronically transferred; will be sent via manual transfer
     * 
     */
    CR,

    /**
     * Prescription not found
     * 
     */
    CS,

    /**
     * Prescription cannot be transferred out because it was previously transferred
     * 
     */
    CT,

    /**
     * Prescription cannot be transferred out because it is voided/cancelled/deactivated
     * 
     */
    CU,

    /**
     * Stop date has been exceeded
     * 
     */
    CV,

    /**
     * Prescription cannot be transferred out because it has expired
     * 
     */
    CW,

    /**
     * Prescription cannot be transferred out by law/regulation
     * 
     */
    CX;

    public String value() {
        return name();
    }

    public static ReasonCode17 fromValue(String v) {
        return valueOf(v);
    }

}
