//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReasonCode11.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReasonCode11">
 *   &lt;restriction base="{}ReasonCode">
 *     &lt;enumeration value="BX"/>
 *     &lt;enumeration value="BY"/>
 *     &lt;enumeration value="CC"/>
 *     &lt;enumeration value="CD"/>
 *     &lt;enumeration value="CE"/>
 *     &lt;enumeration value="CF"/>
 *     &lt;enumeration value="CG"/>
 *     &lt;enumeration value="CP"/>
 *     &lt;enumeration value="CH"/>
 *     &lt;enumeration value="CJ"/>
 *     &lt;enumeration value="CK"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="CM"/>
 *     &lt;enumeration value="CN"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="CY"/>
 *     &lt;enumeration value="FL"/>
 *     &lt;enumeration value="FM"/>
 *     &lt;enumeration value="FN"/>
 *     &lt;enumeration value="FO"/>
 *     &lt;enumeration value="FP"/>
 *     &lt;enumeration value="FQ"/>
 *     &lt;enumeration value="FR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReasonCode11")
@XmlEnum(ReasonCode.class)
public enum ReasonCode11 {


    /**
     * Electronic Prior Authorization not supported. Submit via other methods
     * 
     */
    BX,

    /**
     * Other
     * 
     */
    BY,

    /**
     * Prior Authorization not required for patient/medication
     * 
     */
    CC,

    /**
     * Cannot find matching patient
     * 
     */
    CD,

    /**
     * Patient not eligible (does not have coverage with the payer) 
     * 
     */
    CE,

    /**
     * Prior Authorization duplicate/approved
     * 
     */
    CF,

    /**
     *  Prior Authorization duplicate/in process
     * 
     */
    CG,

    /**
     * The receiver is not the PA processor for this patient and medication combination
     * 
     */
    CP,

    /**
     * Closed by health plan/payer/processor/PBM
     * 
     */
    CH,

    /**
     * Closed by Provider
     * 
     */
    CJ,

    /**
     * Closed by Member
     * 
     */
    CK,

    /**
     * Attachment type (mimetype) not supported
     * 
     */
    CL,

    /**
     * Prescriber not allowed to submit PA request
     * 
     */
    CM,

    /**
     * Response content is inconsistent with the question
     * 
     */
    CN,

    /**
     * The receiver is not the PA processor for this patient
     * 
     */
    CO,

    /**
     * Prior Authorization duplicate/denied
     * 
     */
    CY,

    /**
     * Provider responded after deadline to reply.  PA must be reinitiated
     * 
     */
    FL,

    /**
     * Product not covered by this plan. Prior Authorization not available. (Used when the drug will not be covered even if the provider does a PA)
     * 
     */
    FM,

    /**
     * Prescription within prescribing limits. Prior Authorization not required for PATIENT/MEDICATION. (Used when there are coverage rules in place, but the prescriber is not going outside of them)
     * 
     */
    FN,

    /**
     * Coverage limits may exist for quantity and/or days supply. Plan will pay up to coverage limit. Prior Authorization not required for PATIENT/MEDICATION. (Used when the plan will only pay up to a certain amount, but not above.)
     * 
     */
    FO,

    /**
     * Coverage limits have been exceeded exception not available. Prior Authorization not required for PATIENT/MEDICATION when within coverage limit.
     * 
     */
    FP,

    /**
     * Active PA on file.
     * 
     */
    FQ,

    /**
     * Submitted Product Code is not valid.  Please resolve and resubmit.
     * 
     */
    FR;

    public String value() {
        return name();
    }

    public static ReasonCode11 fromValue(String v) {
        return valueOf(v);
    }

}
