//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REMSApprovedDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REMSApprovedDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="REMSCaseID" type="{}an1..35"/>
 *         &lt;element name="REMSAuthorizationNumber" type="{}an1..140" minOccurs="0"/>
 *         &lt;element name="AuthorizationPeriod" type="{}DateGroupWithEffectiveExpiredDate" minOccurs="0"/>
 *         &lt;element name="REMSNote" type="{}an1..2000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REMSApprovedDetail", propOrder = {
    "remsCaseID",
    "remsAuthorizationNumber",
    "authorizationPeriod",
    "remsNote"
})
public class REMSApprovedDetail {

    @XmlElement(name = "REMSCaseID", required = true)
    protected String remsCaseID;
    @XmlElement(name = "REMSAuthorizationNumber")
    protected String remsAuthorizationNumber;
    @XmlElement(name = "AuthorizationPeriod")
    protected DateGroupWithEffectiveExpiredDate authorizationPeriod;
    @XmlElement(name = "REMSNote")
    protected String remsNote;

    /**
     * Gets the value of the remsCaseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMSCaseID() {
        return remsCaseID;
    }

    /**
     * Sets the value of the remsCaseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMSCaseID(String value) {
        this.remsCaseID = value;
    }

    /**
     * Gets the value of the remsAuthorizationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMSAuthorizationNumber() {
        return remsAuthorizationNumber;
    }

    /**
     * Sets the value of the remsAuthorizationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMSAuthorizationNumber(String value) {
        this.remsAuthorizationNumber = value;
    }

    /**
     * Gets the value of the authorizationPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateGroupWithEffectiveExpiredDate }
     *     
     */
    public DateGroupWithEffectiveExpiredDate getAuthorizationPeriod() {
        return authorizationPeriod;
    }

    /**
     * Sets the value of the authorizationPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateGroupWithEffectiveExpiredDate }
     *     
     */
    public void setAuthorizationPeriod(DateGroupWithEffectiveExpiredDate value) {
        this.authorizationPeriod = value;
    }

    /**
     * Gets the value of the remsNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMSNote() {
        return remsNote;
    }

    /**
     * Sets the value of the remsNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMSNote(String value) {
        this.remsNote = value;
    }

}
