//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REMSResponseChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REMSResponseChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Approved" type="{}REMSApprovedDetail"/>
 *         &lt;element name="Denied" type="{}REMSDeniedType"/>
 *         &lt;element name="Open" type="{}REMSOpenTypeResponse"/>
 *         &lt;element name="Closed" type="{}REMSReasonClosedCodeType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REMSResponseChoiceType", propOrder = {
    "approved",
    "denied",
    "open",
    "closed"
})
public class REMSResponseChoiceType {

    @XmlElement(name = "Approved")
    protected REMSApprovedDetail approved;
    @XmlElement(name = "Denied")
    protected REMSDeniedType denied;
    @XmlElement(name = "Open")
    protected REMSOpenTypeResponse open;
    @XmlElement(name = "Closed")
    protected REMSReasonClosedCodeType closed;

    /**
     * Gets the value of the approved property.
     * 
     * @return
     *     possible object is
     *     {@link REMSApprovedDetail }
     *     
     */
    public REMSApprovedDetail getApproved() {
        return approved;
    }

    /**
     * Sets the value of the approved property.
     * 
     * @param value
     *     allowed object is
     *     {@link REMSApprovedDetail }
     *     
     */
    public void setApproved(REMSApprovedDetail value) {
        this.approved = value;
    }

    /**
     * Gets the value of the denied property.
     * 
     * @return
     *     possible object is
     *     {@link REMSDeniedType }
     *     
     */
    public REMSDeniedType getDenied() {
        return denied;
    }

    /**
     * Sets the value of the denied property.
     * 
     * @param value
     *     allowed object is
     *     {@link REMSDeniedType }
     *     
     */
    public void setDenied(REMSDeniedType value) {
        this.denied = value;
    }

    /**
     * Gets the value of the open property.
     * 
     * @return
     *     possible object is
     *     {@link REMSOpenTypeResponse }
     *     
     */
    public REMSOpenTypeResponse getOpen() {
        return open;
    }

    /**
     * Sets the value of the open property.
     * 
     * @param value
     *     allowed object is
     *     {@link REMSOpenTypeResponse }
     *     
     */
    public void setOpen(REMSOpenTypeResponse value) {
        this.open = value;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link REMSReasonClosedCodeType }
     *     
     */
    public REMSReasonClosedCodeType getClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link REMSReasonClosedCodeType }
     *     
     */
    public void setClosed(REMSReasonClosedCodeType value) {
        this.closed = value;
    }

}
