//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouteOfAdministration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteOfAdministration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RouteOfAdministrationCode" type="{}RouteOfAdministrationCode" minOccurs="0"/>
 *         &lt;element name="MultipleRouteOfAdministrationModifier" type="{}ANDOR" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteOfAdministration", propOrder = {
    "routeOfAdministrationCode",
    "multipleRouteOfAdministrationModifier"
})
public class RouteOfAdministration {

    @XmlElement(name = "RouteOfAdministrationCode")
    protected RouteOfAdministrationCode routeOfAdministrationCode;
    @XmlElement(name = "MultipleRouteOfAdministrationModifier")
    protected String multipleRouteOfAdministrationModifier;

    /**
     * Gets the value of the routeOfAdministrationCode property.
     * 
     * @return
     *     possible object is
     *     {@link RouteOfAdministrationCode }
     *     
     */
    public RouteOfAdministrationCode getRouteOfAdministrationCode() {
        return routeOfAdministrationCode;
    }

    /**
     * Sets the value of the routeOfAdministrationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteOfAdministrationCode }
     *     
     */
    public void setRouteOfAdministrationCode(RouteOfAdministrationCode value) {
        this.routeOfAdministrationCode = value;
    }

    /**
     * Gets the value of the multipleRouteOfAdministrationModifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleRouteOfAdministrationModifier() {
        return multipleRouteOfAdministrationModifier;
    }

    /**
     * Sets the value of the multipleRouteOfAdministrationModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleRouteOfAdministrationModifier(String value) {
        this.multipleRouteOfAdministrationModifier = value;
    }

}
