//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RxChangeCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RxChangeCode">
 *   &lt;restriction base="{}MessageFunctionCode">
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="OS"/>
 *     &lt;enumeration value="U"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RxChangeCode")
@XmlEnum(MessageFunctionCode.class)
public enum RxChangeCode {


    /**
     * Generic Substitution - A modification of the product prescribed to a generic equivalent.			
     * 
     * 
     */
    G,

    /**
     * Prior Authorization Required - A request to obtain prior authorization before dispensing.
     * 
     */
    P,

    /**
     * Therapeutic Interchange/Substitution - A modification of the product prescribed to a preferred product choice.
     * 
     */
    T,

    /**
     * Drug Use Evaluation
     * 
     */
    D,

    /**
     * Script Clarification
     * 
     */
    S,

    /**
     * Pharmacy is out of stock of the medication prescribed and it cannot be obtained in a clinically appropriate timeframe.
     * 
     */
    OS,

    /**
     * Prescriber Authorization – Resolution of the prescriber authorization conflict related to state/federal regulatory requirements is required before dispensing.
     * 
     */
    U;

    public String value() {
        return name();
    }

    public static RxChangeCode fromValue(String v) {
        return valueOf(v);
    }

}
