//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This transaction is sent from a pharmacy to a prescriber to request a change on a new prescription, for example, to request generic substitution. It may request a change on a fillable prescription. It may also be utilized to request a prescriber to review the drug requested, and obtain a Prior Authorization from the payer for the prescription.
 * 
 * <p>Java class for RxChangeRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RxChangeRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{}SCRIPTRequest">
 *       &lt;sequence>
 *         &lt;element name="MessageRequestCode" type="{}RxChangeCode"/>
 *         &lt;element name="MessageRequestSubCode" type="{}MessageRequestSubCode" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="ReturnReceipt" type="{}an1..3" minOccurs="0"/>
 *         &lt;element name="RequestReferenceNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="UrgencyIndicatorCode" type="{}UrgencyIndicatorCode" minOccurs="0"/>
 *         &lt;element name="FollowUpRequest" type="{}n1..1" minOccurs="0"/>
 *         &lt;element name="ChangeOfPrescriptionStatusFlag" type="{}ChangeOfPrescriptionStatusCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="AllergyOrAdverseEvent" type="{}AllergyRestrictedChoice" minOccurs="0"/>
 *         &lt;element name="BenefitsCoordination" type="{}BenefitsCoordination" maxOccurs="4" minOccurs="0"/>
 *         &lt;element name="DiagnosisGeneral" type="{}DiagnosisGeneral" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Facility" type="{}Facility" minOccurs="0"/>
 *         &lt;element name="FillStatus" type="{}FillStatus" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Patient" type="{}PatientTypeWithSubstanceUse"/>
 *         &lt;element name="Pharmacy" type="{}MandatoryPharmacy"/>
 *         &lt;element name="Prescriber" type="{}PrescriberChoice"/>
 *         &lt;element name="DispensingRequestCode" type="{}DispensingRequestCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="DrugAdministrationRequest" type="{}DrugAdministrationRequest" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Observation" type="{}Observation" minOccurs="0"/>
 *         &lt;element name="MedicationDispensed" type="{}PrescribedMedication" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="MedicationPrescribed" type="{}PrescribedMedication"/>
 *         &lt;element name="MedicationRequested" type="{}RequestedMedication" maxOccurs="9" minOccurs="0"/>
 *         &lt;element name="Supervisor" type="{}SupervisorType" minOccurs="0"/>
 *         &lt;element name="RequestedDates" type="{}DateRange" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ProhibitRenewalRequest" type="{http://www.w3.org/2001/XMLSchema}boolean" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ChangeReasonText" type="{}an1..260" minOccurs="0"/>
 *         &lt;element name="FollowUpPrescriber" type="{}FollowUpPrescriberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RxChangeRequest")
public class RxChangeRequest
    extends SCRIPTRequest
{


}
