//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This response is sent from an entity to an entity to describe the patient’s medication history.
 * 
 * <p>Java class for RxHistoryResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RxHistoryResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageRequestCode" type="{}MessageFunctionCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ReturnReceipt" type="{}an1..3" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="RequestReferenceNumber" type="{}an1..35" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ChangeOfPrescriptionStatusFlag" type="{}ChangeOfPrescriptionStatusCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Response" type="{}RxHistoryResponseType"/>
 *         &lt;element name="BenefitsCoordination" type="{}RxHistoryBenefitsCoordination" maxOccurs="4"/>
 *         &lt;element name="Facility" type="{}Facility" minOccurs="0"/>
 *         &lt;element name="Patient" type="{}PatientType"/>
 *         &lt;element name="Pharmacy" type="{}OptionalPharmacy" minOccurs="0"/>
 *         &lt;element name="Prescriber" type="{}HistoryPrescriberChoice" minOccurs="0"/>
 *         &lt;element name="Observation" type="{}Observation" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Supervisor" type="{}SupervisorType" maxOccurs="0" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="MedicationDispensed" type="{}HistoryDispensedMedication" maxOccurs="300"/>
 *           &lt;element name="MedicationDispensedAdministered" type="{}HistoryDispensedMedication" maxOccurs="300"/>
 *           &lt;element name="MedicationPrescribed" type="{}HistoryPrescribedMedication" maxOccurs="300"/>
 *         &lt;/choice>
 *         &lt;element name="RequestedDates" type="{}DateRange"/>
 *         &lt;element name="Scores" type="{}ScoreType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PDMPStatesResponded" type="{}PDMPStateResponded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RxHistoryResponse", propOrder = {
    "response",
    "benefitsCoordination",
    "facility",
    "patient",
    "pharmacy",
    "prescriber",
    "medicationDispensed",
    "medicationDispensedAdministered",
    "medicationPrescribed",
    "requestedDates",
    "scores",
    "pdmpStatesResponded"
})
public class RxHistoryResponse {

    @XmlElement(name = "Response", required = true)
    protected RxHistoryResponseType response;
    @XmlElement(name = "BenefitsCoordination", required = true)
    protected List<RxHistoryBenefitsCoordination> benefitsCoordination;
    @XmlElement(name = "Facility")
    protected Facility facility;
    @XmlElement(name = "Patient", required = true)
    protected PatientType patient;
    @XmlElement(name = "Pharmacy")
    protected OptionalPharmacy pharmacy;
    @XmlElement(name = "Prescriber")
    protected HistoryPrescriberChoice prescriber;
    @XmlElement(name = "MedicationDispensed")
    protected List<HistoryDispensedMedication> medicationDispensed;
    @XmlElement(name = "MedicationDispensedAdministered")
    protected List<HistoryDispensedMedication> medicationDispensedAdministered;
    @XmlElement(name = "MedicationPrescribed")
    protected List<HistoryPrescribedMedication> medicationPrescribed;
    @XmlElement(name = "RequestedDates", required = true)
    protected DateRange requestedDates;
    @XmlElement(name = "Scores")
    protected List<ScoreType> scores;
    @XmlElement(name = "PDMPStatesResponded")
    protected PDMPStateResponded pdmpStatesResponded;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link RxHistoryResponseType }
     *     
     */
    public RxHistoryResponseType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxHistoryResponseType }
     *     
     */
    public void setResponse(RxHistoryResponseType value) {
        this.response = value;
    }

    /**
     * Gets the value of the benefitsCoordination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the benefitsCoordination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBenefitsCoordination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RxHistoryBenefitsCoordination }
     * 
     * 
     */
    public List<RxHistoryBenefitsCoordination> getBenefitsCoordination() {
        if (benefitsCoordination == null) {
            benefitsCoordination = new ArrayList<RxHistoryBenefitsCoordination>();
        }
        return this.benefitsCoordination;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link Facility }
     *     
     */
    public Facility getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Facility }
     *     
     */
    public void setFacility(Facility value) {
        this.facility = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType }
     *     
     */
    public PatientType getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType }
     *     
     */
    public void setPatient(PatientType value) {
        this.patient = value;
    }

    /**
     * Gets the value of the pharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalPharmacy }
     *     
     */
    public OptionalPharmacy getPharmacy() {
        return pharmacy;
    }

    /**
     * Sets the value of the pharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalPharmacy }
     *     
     */
    public void setPharmacy(OptionalPharmacy value) {
        this.pharmacy = value;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryPrescriberChoice }
     *     
     */
    public HistoryPrescriberChoice getPrescriber() {
        return prescriber;
    }

    /**
     * Sets the value of the prescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryPrescriberChoice }
     *     
     */
    public void setPrescriber(HistoryPrescriberChoice value) {
        this.prescriber = value;
    }

    /**
     * Gets the value of the medicationDispensed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationDispensed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationDispensed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HistoryDispensedMedication }
     * 
     * 
     */
    public List<HistoryDispensedMedication> getMedicationDispensed() {
        if (medicationDispensed == null) {
            medicationDispensed = new ArrayList<HistoryDispensedMedication>();
        }
        return this.medicationDispensed;
    }

    /**
     * Gets the value of the medicationDispensedAdministered property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationDispensedAdministered property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationDispensedAdministered().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HistoryDispensedMedication }
     * 
     * 
     */
    public List<HistoryDispensedMedication> getMedicationDispensedAdministered() {
        if (medicationDispensedAdministered == null) {
            medicationDispensedAdministered = new ArrayList<HistoryDispensedMedication>();
        }
        return this.medicationDispensedAdministered;
    }

    /**
     * Gets the value of the medicationPrescribed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationPrescribed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationPrescribed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HistoryPrescribedMedication }
     * 
     * 
     */
    public List<HistoryPrescribedMedication> getMedicationPrescribed() {
        if (medicationPrescribed == null) {
            medicationPrescribed = new ArrayList<HistoryPrescribedMedication>();
        }
        return this.medicationPrescribed;
    }

    /**
     * Gets the value of the requestedDates property.
     * 
     * @return
     *     possible object is
     *     {@link DateRange }
     *     
     */
    public DateRange getRequestedDates() {
        return requestedDates;
    }

    /**
     * Sets the value of the requestedDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRange }
     *     
     */
    public void setRequestedDates(DateRange value) {
        this.requestedDates = value;
    }

    /**
     * Gets the value of the scores property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scores property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScores().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreType }
     * 
     * 
     */
    public List<ScoreType> getScores() {
        if (scores == null) {
            scores = new ArrayList<ScoreType>();
        }
        return this.scores;
    }

    /**
     * Gets the value of the pdmpStatesResponded property.
     * 
     * @return
     *     possible object is
     *     {@link PDMPStateResponded }
     *     
     */
    public PDMPStateResponded getPDMPStatesResponded() {
        return pdmpStatesResponded;
    }

    /**
     * Sets the value of the pdmpStatesResponded property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDMPStateResponded }
     *     
     */
    public void setPDMPStatesResponded(PDMPStateResponded value) {
        this.pdmpStatesResponded = value;
    }

}
