//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This transaction is the response to a request for additional refills (RxRenewalRequest). The response may be accepted or denied. The response may be a new prescription (replace).
 * 
 * <p>Java class for RxRenewalResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RxRenewalResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{}SCRIPTResponse">
 *       &lt;sequence>
 *         &lt;element name="MessageRequestCode" type="{}MessageFunctionCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="ReturnReceipt" type="{}an1..3" minOccurs="0"/>
 *         &lt;element name="RequestReferenceNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="UrgencyIndicatorCode" type="{}UrgencyIndicatorCode" minOccurs="0"/>
 *         &lt;element name="ChangeOfPrescriptionStatusFlag" type="{}ChangeOfPrescriptionStatusCode" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Response" type="{}RefillResponseType"/>
 *         &lt;element name="AllergyOrAdverseEvent" type="{}AllergyRestrictedChoice" minOccurs="0"/>
 *         &lt;element name="BenefitsCoordination" type="{}BaseBenefitsCoordination" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="Facility" type="{}Facility" minOccurs="0"/>
 *         &lt;element name="Patient" type="{}PatientTypeWithSubstanceUse"/>
 *         &lt;element name="Pharmacy" type="{}Pharmacy"/>
 *         &lt;element name="Prescriber" type="{}PrescriberChoice"/>
 *         &lt;element name="Observation" type="{}Observation" minOccurs="0"/>
 *         &lt;element name="Supervisor" type="{}SupervisorType" minOccurs="0"/>
 *         &lt;element name="MedicationDispensed" type="{}RefillResponseDispensedMedication" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="MedicationPrescribed" type="{}PrescribedMedication" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="MedicationDispensedAdministered" type="{}Medication" maxOccurs="0" minOccurs="0"/>
 *         &lt;element name="MedicationResponse" type="{}RefillResponseReplacedMedication"/>
 *         &lt;element name="FollowUpPrescriber" type="{}FollowUpPrescriberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RxRenewalResponse")
public class RxRenewalResponse
    extends SCRIPTResponse
{


}
