//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SCRIPTResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SCRIPTResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageRequestCode" type="{}MessageFunctionCode" minOccurs="0"/>
 *         &lt;element name="MessageRequestSubCode" type="{}MessageRequestSubCode" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="ReturnReceipt" type="{}an1..3" minOccurs="0"/>
 *         &lt;element name="RequestReferenceNumber" type="{}an1..35" minOccurs="0"/>
 *         &lt;element name="UrgencyIndicatorCode" type="{}UrgencyIndicatorCode" minOccurs="0"/>
 *         &lt;element name="ChangeOfPrescriptionStatusFlag" type="{}ChangeOfPrescriptionStatusCode" minOccurs="0"/>
 *         &lt;element name="Response" type="{}ResponseAbstractType" minOccurs="0"/>
 *         &lt;element name="AllergyOrAdverseEvent" type="{}AllergyChoice" minOccurs="0"/>
 *         &lt;element name="BenefitsCoordination" type="{}BaseBenefitsCoordination" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Facility" type="{}Facility" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Patient" type="{}PatientFullTypeAbstract" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Pharmacy" type="{}Pharmacy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Prescriber" type="{}HistoryPrescriberChoice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Observation" type="{}Observation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Supervisor" type="{}SupervisorTypeAbstract" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MedicationDispensed" type="{}MedicationAbstract" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MedicationDispensedAdministered" type="{}MedicationAbstract" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MedicationPrescribed" type="{}MedicationAbstract" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MedicationResponse" type="{}RefillResponseReplacedMedication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FollowUpPrescriber" type="{}FollowUpPrescriberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SCRIPTResponse", propOrder = {
    "messageRequestCode",
    "messageRequestSubCode",
    "returnReceipt",
    "requestReferenceNumber",
    "urgencyIndicatorCode",
    "changeOfPrescriptionStatusFlag",
    "response",
    "allergyOrAdverseEvent",
    "benefitsCoordination",
    "facility",
    "patient",
    "pharmacy",
    "prescriber",
    "observation",
    "supervisor",
    "medicationDispensed",
    "medicationDispensedAdministered",
    "medicationPrescribed",
    "medicationResponse",
    "followUpPrescriber"
})
@XmlSeeAlso({
    RxChangeResponse.class,
    CancelRxResponse.class,
    RxRenewalResponse.class
})
public abstract class SCRIPTResponse {

    @XmlElement(name = "MessageRequestCode")
    @XmlSchemaType(name = "string")
    protected MessageFunctionCode messageRequestCode;
    @XmlElement(name = "MessageRequestSubCode")
    @XmlSchemaType(name = "string")
    protected List<MessageRequestSubCode> messageRequestSubCode;
    @XmlElement(name = "ReturnReceipt")
    protected String returnReceipt;
    @XmlElement(name = "RequestReferenceNumber")
    protected String requestReferenceNumber;
    @XmlElement(name = "UrgencyIndicatorCode")
    @XmlSchemaType(name = "string")
    protected UrgencyIndicatorCode urgencyIndicatorCode;
    @XmlElement(name = "ChangeOfPrescriptionStatusFlag")
    @XmlSchemaType(name = "string")
    protected ChangeOfPrescriptionStatusCode changeOfPrescriptionStatusFlag;
    @XmlElement(name = "Response")
    protected ResponseAbstractType response;
    @XmlElement(name = "AllergyOrAdverseEvent")
    protected AllergyChoice allergyOrAdverseEvent;
    @XmlElement(name = "BenefitsCoordination")
    protected List<BaseBenefitsCoordination> benefitsCoordination;
    @XmlElement(name = "Facility")
    protected List<Facility> facility;
    @XmlElement(name = "Patient")
    protected List<PatientFullTypeAbstract> patient;
    @XmlElement(name = "Pharmacy")
    protected List<Pharmacy> pharmacy;
    @XmlElement(name = "Prescriber")
    protected List<HistoryPrescriberChoice> prescriber;
    @XmlElement(name = "Observation")
    protected List<Observation> observation;
    @XmlElement(name = "Supervisor")
    protected List<SupervisorTypeAbstract> supervisor;
    @XmlElement(name = "MedicationDispensed")
    protected List<MedicationAbstract> medicationDispensed;
    @XmlElement(name = "MedicationDispensedAdministered")
    protected List<MedicationAbstract> medicationDispensedAdministered;
    @XmlElement(name = "MedicationPrescribed")
    protected List<MedicationAbstract> medicationPrescribed;
    @XmlElement(name = "MedicationResponse")
    protected List<RefillResponseReplacedMedication> medicationResponse;
    @XmlElement(name = "FollowUpPrescriber")
    protected FollowUpPrescriberType followUpPrescriber;

    /**
     * Gets the value of the messageRequestCode property.
     * 
     * @return
     *     possible object is
     *     {@link MessageFunctionCode }
     *     
     */
    public MessageFunctionCode getMessageRequestCode() {
        return messageRequestCode;
    }

    /**
     * Sets the value of the messageRequestCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageFunctionCode }
     *     
     */
    public void setMessageRequestCode(MessageFunctionCode value) {
        this.messageRequestCode = value;
    }

    /**
     * Gets the value of the messageRequestSubCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageRequestSubCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageRequestSubCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageRequestSubCode }
     * 
     * 
     */
    public List<MessageRequestSubCode> getMessageRequestSubCode() {
        if (messageRequestSubCode == null) {
            messageRequestSubCode = new ArrayList<MessageRequestSubCode>();
        }
        return this.messageRequestSubCode;
    }

    /**
     * Gets the value of the returnReceipt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnReceipt() {
        return returnReceipt;
    }

    /**
     * Sets the value of the returnReceipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnReceipt(String value) {
        this.returnReceipt = value;
    }

    /**
     * Gets the value of the requestReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestReferenceNumber() {
        return requestReferenceNumber;
    }

    /**
     * Sets the value of the requestReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestReferenceNumber(String value) {
        this.requestReferenceNumber = value;
    }

    /**
     * Gets the value of the urgencyIndicatorCode property.
     * 
     * @return
     *     possible object is
     *     {@link UrgencyIndicatorCode }
     *     
     */
    public UrgencyIndicatorCode getUrgencyIndicatorCode() {
        return urgencyIndicatorCode;
    }

    /**
     * Sets the value of the urgencyIndicatorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrgencyIndicatorCode }
     *     
     */
    public void setUrgencyIndicatorCode(UrgencyIndicatorCode value) {
        this.urgencyIndicatorCode = value;
    }

    /**
     * Gets the value of the changeOfPrescriptionStatusFlag property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeOfPrescriptionStatusCode }
     *     
     */
    public ChangeOfPrescriptionStatusCode getChangeOfPrescriptionStatusFlag() {
        return changeOfPrescriptionStatusFlag;
    }

    /**
     * Sets the value of the changeOfPrescriptionStatusFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeOfPrescriptionStatusCode }
     *     
     */
    public void setChangeOfPrescriptionStatusFlag(ChangeOfPrescriptionStatusCode value) {
        this.changeOfPrescriptionStatusFlag = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseAbstractType }
     *     
     */
    public ResponseAbstractType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseAbstractType }
     *     
     */
    public void setResponse(ResponseAbstractType value) {
        this.response = value;
    }

    /**
     * Gets the value of the allergyOrAdverseEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AllergyChoice }
     *     
     */
    public AllergyChoice getAllergyOrAdverseEvent() {
        return allergyOrAdverseEvent;
    }

    /**
     * Sets the value of the allergyOrAdverseEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllergyChoice }
     *     
     */
    public void setAllergyOrAdverseEvent(AllergyChoice value) {
        this.allergyOrAdverseEvent = value;
    }

    /**
     * Gets the value of the benefitsCoordination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the benefitsCoordination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBenefitsCoordination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseBenefitsCoordination }
     * 
     * 
     */
    public List<BaseBenefitsCoordination> getBenefitsCoordination() {
        if (benefitsCoordination == null) {
            benefitsCoordination = new ArrayList<BaseBenefitsCoordination>();
        }
        return this.benefitsCoordination;
    }

    /**
     * Gets the value of the facility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Facility }
     * 
     * 
     */
    public List<Facility> getFacility() {
        if (facility == null) {
            facility = new ArrayList<Facility>();
        }
        return this.facility;
    }

    /**
     * Gets the value of the patient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatientFullTypeAbstract }
     * 
     * 
     */
    public List<PatientFullTypeAbstract> getPatient() {
        if (patient == null) {
            patient = new ArrayList<PatientFullTypeAbstract>();
        }
        return this.patient;
    }

    /**
     * Gets the value of the pharmacy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pharmacy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPharmacy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pharmacy }
     * 
     * 
     */
    public List<Pharmacy> getPharmacy() {
        if (pharmacy == null) {
            pharmacy = new ArrayList<Pharmacy>();
        }
        return this.pharmacy;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prescriber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrescriber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HistoryPrescriberChoice }
     * 
     * 
     */
    public List<HistoryPrescriberChoice> getPrescriber() {
        if (prescriber == null) {
            prescriber = new ArrayList<HistoryPrescriberChoice>();
        }
        return this.prescriber;
    }

    /**
     * Gets the value of the observation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Observation }
     * 
     * 
     */
    public List<Observation> getObservation() {
        if (observation == null) {
            observation = new ArrayList<Observation>();
        }
        return this.observation;
    }

    /**
     * Gets the value of the supervisor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supervisor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupervisor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupervisorTypeAbstract }
     * 
     * 
     */
    public List<SupervisorTypeAbstract> getSupervisor() {
        if (supervisor == null) {
            supervisor = new ArrayList<SupervisorTypeAbstract>();
        }
        return this.supervisor;
    }

    /**
     * Gets the value of the medicationDispensed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationDispensed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationDispensed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationAbstract }
     * 
     * 
     */
    public List<MedicationAbstract> getMedicationDispensed() {
        if (medicationDispensed == null) {
            medicationDispensed = new ArrayList<MedicationAbstract>();
        }
        return this.medicationDispensed;
    }

    /**
     * Gets the value of the medicationDispensedAdministered property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationDispensedAdministered property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationDispensedAdministered().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationAbstract }
     * 
     * 
     */
    public List<MedicationAbstract> getMedicationDispensedAdministered() {
        if (medicationDispensedAdministered == null) {
            medicationDispensedAdministered = new ArrayList<MedicationAbstract>();
        }
        return this.medicationDispensedAdministered;
    }

    /**
     * Gets the value of the medicationPrescribed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationPrescribed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationPrescribed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationAbstract }
     * 
     * 
     */
    public List<MedicationAbstract> getMedicationPrescribed() {
        if (medicationPrescribed == null) {
            medicationPrescribed = new ArrayList<MedicationAbstract>();
        }
        return this.medicationPrescribed;
    }

    /**
     * Gets the value of the medicationResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefillResponseReplacedMedication }
     * 
     * 
     */
    public List<RefillResponseReplacedMedication> getMedicationResponse() {
        if (medicationResponse == null) {
            medicationResponse = new ArrayList<RefillResponseReplacedMedication>();
        }
        return this.medicationResponse;
    }

    /**
     * Gets the value of the followUpPrescriber property.
     * 
     * @return
     *     possible object is
     *     {@link FollowUpPrescriberType }
     *     
     */
    public FollowUpPrescriberType getFollowUpPrescriber() {
        return followUpPrescriber;
    }

    /**
     * Sets the value of the followUpPrescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link FollowUpPrescriberType }
     *     
     */
    public void setFollowUpPrescriber(FollowUpPrescriberType value) {
        this.followUpPrescriber = value;
    }

}
