//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecondaryDiagnosisCodeQualifierCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecondaryDiagnosisCodeQualifierCode">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="ABF"/>
 *     &lt;enumeration value="DX"/>
 *     &lt;enumeration value="LD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SecondaryDiagnosisCodeQualifierCode")
@XmlEnum
public enum SecondaryDiagnosisCodeQualifierCode {


    /**
     * International Classification of Diseases-10- Clinical Modifications
     * 
     */
    ABF,

    /**
     * International Classification of Diseases-9- Clinical Modifications-Diagnosis
     * 
     */
    DX,

    /**
     * SNOMED - Systematized Nomenclature of Medicine Clinical Terms® (SNOMED CT). SNOMED CT® terminology which is available from the Health Terminology Standards Development Organisation (IHTSDO) http://www.ihtsdo.org/snomed-ct/
     * 
     */
    LD;

    public String value() {
        return name();
    }

    public static SecondaryDiagnosisCodeQualifierCode fromValue(String v) {
        return valueOf(v);
    }

}
