//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SenderSoftwareType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SenderSoftwareType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SenderSoftwareDeveloper" type="{}an1..35"/>
 *         &lt;element name="SenderSoftwareProduct" type="{}an1..35"/>
 *         &lt;element name="SenderSoftwareVersionRelease" type="{}an1..50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SenderSoftwareType", propOrder = {
    "senderSoftwareDeveloper",
    "senderSoftwareProduct",
    "senderSoftwareVersionRelease"
})
public class SenderSoftwareType {

    @XmlElement(name = "SenderSoftwareDeveloper", required = true)
    protected String senderSoftwareDeveloper;
    @XmlElement(name = "SenderSoftwareProduct", required = true)
    protected String senderSoftwareProduct;
    @XmlElement(name = "SenderSoftwareVersionRelease", required = true)
    protected String senderSoftwareVersionRelease;

    /**
     * Gets the value of the senderSoftwareDeveloper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderSoftwareDeveloper() {
        return senderSoftwareDeveloper;
    }

    /**
     * Sets the value of the senderSoftwareDeveloper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderSoftwareDeveloper(String value) {
        this.senderSoftwareDeveloper = value;
    }

    /**
     * Gets the value of the senderSoftwareProduct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderSoftwareProduct() {
        return senderSoftwareProduct;
    }

    /**
     * Sets the value of the senderSoftwareProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderSoftwareProduct(String value) {
        this.senderSoftwareProduct = value;
    }

    /**
     * Gets the value of the senderSoftwareVersionRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderSoftwareVersionRelease() {
        return senderSoftwareVersionRelease;
    }

    /**
     * Sets the value of the senderSoftwareVersionRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderSoftwareVersionRelease(String value) {
        this.senderSoftwareVersionRelease = value;
    }

}
