//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SigText" type="{}an1..1000"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="CodeSystem">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="SNOMEDVersion" type="{}an"/>
 *                     &lt;element name="FMTVersion" type="{}an"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Instruction" type="{}Instruction"/>
 *           &lt;sequence maxOccurs="49" minOccurs="0">
 *             &lt;element name="MultipleInstructionModifier" type="{}ANDORTHENNOT"/>
 *             &lt;element name="Instruction" type="{}Instruction"/>
 *           &lt;/sequence>
 *           &lt;sequence maxOccurs="50" minOccurs="0">
 *             &lt;element name="IndicationForUse" type="{}Indication"/>
 *           &lt;/sequence>
 *           &lt;element name="MaximumDoseRestriction" type="{}MaximumDoseRestriction" maxOccurs="50" minOccurs="0"/>
 *           &lt;element name="ClarifyingFreeText" type="{}an1..255" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sig", propOrder = {
    "seq2"
})
public class Sig {

    @XmlElementRefs({
        @XmlElementRef(name = "SigText", type = JAXBElement.class),
        @XmlElementRef(name = "CodeSystem", type = JAXBElement.class),
        @XmlElementRef(name = "ClarifyingFreeText", type = JAXBElement.class),
        @XmlElementRef(name = "Instruction", type = JAXBElement.class),
        @XmlElementRef(name = "IndicationForUse", type = JAXBElement.class),
        @XmlElementRef(name = "MaximumDoseRestriction", type = JAXBElement.class),
        @XmlElementRef(name = "MultipleInstructionModifier", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> seq2;

    /**
     * Gets the value of the seq2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the seq2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeq2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Sig.CodeSystem }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Instruction }{@code >}
     * {@link JAXBElement }{@code <}{@link Indication }{@code >}
     * {@link JAXBElement }{@code <}{@link MaximumDoseRestriction }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getSeq2() {
        if (seq2 == null) {
            seq2 = new ArrayList<JAXBElement<?>>();
        }
        return this.seq2;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SNOMEDVersion" type="{}an"/>
     *         &lt;element name="FMTVersion" type="{}an"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "snomedVersion",
        "fmtVersion"
    })
    public static class CodeSystem {

        @XmlElement(name = "SNOMEDVersion", required = true)
        protected String snomedVersion;
        @XmlElement(name = "FMTVersion", required = true)
        protected String fmtVersion;

        /**
         * Gets the value of the snomedVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSNOMEDVersion() {
            return snomedVersion;
        }

        /**
         * Sets the value of the snomedVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSNOMEDVersion(String value) {
            this.snomedVersion = value;
        }

        /**
         * Gets the value of the fmtVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFMTVersion() {
            return fmtVersion;
        }

        /**
         * Sets the value of the fmtVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFMTVersion(String value) {
            this.fmtVersion = value;
        }

    }

}
