//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * SNOMED Adverse Event Code Constraint for Allergies
 * 
 * <p>Java class for SNOMEDAdverseEventCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SNOMEDAdverseEventCode">
 *   &lt;complexContent>
 *     &lt;restriction base="{}SNOMEDCode">
 *       &lt;sequence>
 *         &lt;element name="Text" type="{}an"/>
 *         &lt;element name="Code" type="{}eclSNOMEDAdverseEventCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SNOMEDAdverseEventCode")
public class SNOMEDAdverseEventCode
    extends SNOMEDCode
{


}
