//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceOfInformation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SourceOfInformation">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="C"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SourceOfInformation")
@XmlEnum
public enum SourceOfInformation {


    /**
     * Indicates information is provided by the patient or patient representative or personal health record (PHR)
     * 
     */
    P,

    /**
     * Indicates information is provided by a clinician or provider
     * 
     */
    C;

    public String value() {
        return name();
    }

    public static SourceOfInformation fromValue(String v) {
        return valueOf(v);
    }

}
