//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecializedResponseAbstractType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecializedResponseAbstractType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Denied" type="{}SpecializedDeniedAbstractType" minOccurs="0"/>
 *         &lt;element name="Approved" type="{}SpecializedApprovedAbstractType" minOccurs="0"/>
 *         &lt;element name="ApprovedWithChanges" type="{}ApprovedWithChangesType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecializedResponseAbstractType", propOrder = {
    "denied",
    "approved",
    "approvedWithChanges"
})
@XmlSeeAlso({
    MTMResponseType.class,
    CFProductInquiryResponseType.class,
    ClinicalInformationResponseType.class,
    CFRxOrderCancelResponseType.class
})
public class SpecializedResponseAbstractType {

    @XmlElement(name = "Denied")
    protected SpecializedDeniedAbstractType denied;
    @XmlElement(name = "Approved")
    protected SpecializedApprovedAbstractType approved;
    @XmlElement(name = "ApprovedWithChanges")
    protected ApprovedWithChangesType approvedWithChanges;

    /**
     * Gets the value of the denied property.
     * 
     * @return
     *     possible object is
     *     {@link SpecializedDeniedAbstractType }
     *     
     */
    public SpecializedDeniedAbstractType getDenied() {
        return denied;
    }

    /**
     * Sets the value of the denied property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecializedDeniedAbstractType }
     *     
     */
    public void setDenied(SpecializedDeniedAbstractType value) {
        this.denied = value;
    }

    /**
     * Gets the value of the approved property.
     * 
     * @return
     *     possible object is
     *     {@link SpecializedApprovedAbstractType }
     *     
     */
    public SpecializedApprovedAbstractType getApproved() {
        return approved;
    }

    /**
     * Sets the value of the approved property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecializedApprovedAbstractType }
     *     
     */
    public void setApproved(SpecializedApprovedAbstractType value) {
        this.approved = value;
    }

    /**
     * Gets the value of the approvedWithChanges property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovedWithChangesType }
     *     
     */
    public ApprovedWithChangesType getApprovedWithChanges() {
        return approvedWithChanges;
    }

    /**
     * Sets the value of the approvedWithChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovedWithChangesType }
     *     
     */
    public void setApprovedWithChanges(ApprovedWithChangesType value) {
        this.approvedWithChanges = value;
    }

}
