//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Used in MTMServiceRequest, MTMServiceResponse
 * 
 * <p>Java class for SpecializedServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecializedServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{}GlobalServiceType">
 *       &lt;sequence>
 *         &lt;element name="MTMPayerCaseIdentifier" type="{}an" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="TypeOfServiceFreeText" type="{}an"/>
 *           &lt;element name="TypeOfService" type="{}QualifiedCodeWithText"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="TargetedTypeOfServiceFreeText" type="{}an"/>
 *           &lt;element name="TargetedTypeOfService" type="{}QualifiedCodeWithText"/>
 *         &lt;/choice>
 *         &lt;element name="EffectiveDate" type="{}DateType" minOccurs="0"/>
 *         &lt;element name="ExpirationDate" type="{}DateType" minOccurs="0"/>
 *         &lt;element name="TotalNumberOfEncountersApproved" type="{}n1..4" minOccurs="0"/>
 *         &lt;element name="FrequencyOfEncountersApproved" type="{}QualifiedCodeWithText" minOccurs="0"/>
 *         &lt;element name="DateOfService" type="{}SimpleDateType" maxOccurs="0" minOccurs="0"/>
 *         &lt;choice maxOccurs="0" minOccurs="0">
 *           &lt;element name="ResultOfActionFreeText" type="{}an"/>
 *           &lt;element name="ResultOfAction" type="{}QualifiedCodeWithText"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ReasonForMTMServiceFreeText" type="{}an"/>
 *           &lt;element name="ReasonForMTMService" type="{}QualifiedCodeWithText"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="0" minOccurs="0">
 *           &lt;element name="MTMActionFreeText" type="{}an"/>
 *           &lt;element name="MTMAction" type="{}QualifiedCodeWithText"/>
 *         &lt;/choice>
 *         &lt;element name="TypeOfServiceGroupSetting" type="{}an" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecializedServiceType")
public class SpecializedServiceType
    extends GlobalServiceType
{


}
