//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Substances complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Substances">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{}SigCode"/>
 *         &lt;element name="Level" type="{}SigCode" minOccurs="0"/>
 *         &lt;element name="RouteOfAdministration" type="{}SigCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Substances", propOrder = {
    "type",
    "level",
    "routeOfAdministration"
})
public class Substances {

    @XmlElement(name = "Type", required = true)
    protected SigCode type;
    @XmlElement(name = "Level")
    protected SigCode level;
    @XmlElement(name = "RouteOfAdministration")
    protected SigCode routeOfAdministration;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SigCode }
     *     
     */
    public SigCode getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SigCode }
     *     
     */
    public void setType(SigCode value) {
        this.type = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link SigCode }
     *     
     */
    public SigCode getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link SigCode }
     *     
     */
    public void setLevel(SigCode value) {
        this.level = value;
    }

    /**
     * Gets the value of the routeOfAdministration property.
     * 
     * @return
     *     possible object is
     *     {@link SigCode }
     *     
     */
    public SigCode getRouteOfAdministration() {
        return routeOfAdministration;
    }

    /**
     * Sets the value of the routeOfAdministration property.
     * 
     * @param value
     *     allowed object is
     *     {@link SigCode }
     *     
     */
    public void setRouteOfAdministration(SigCode value) {
        this.routeOfAdministration = value;
    }

}
