//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupervisorTypeAbstract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupervisorTypeAbstract">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="NonVeterinarian" type="{}SupervisorOptional"/>
 *         &lt;element name="Veterinarian" type="{}VetSupervisorMirrorSupervisorOptional"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupervisorTypeAbstract", propOrder = {
    "nonVeterinarian",
    "veterinarian"
})
@XmlSeeAlso({
    SupervisorType.class,
    SupervisorOptionalType.class,
    SupervisorMandatoryAddressType.class
})
public class SupervisorTypeAbstract {

    @XmlElement(name = "NonVeterinarian")
    protected SupervisorOptional nonVeterinarian;
    @XmlElement(name = "Veterinarian")
    protected VetSupervisorMirrorSupervisorOptional veterinarian;

    /**
     * Gets the value of the nonVeterinarian property.
     * 
     * @return
     *     possible object is
     *     {@link SupervisorOptional }
     *     
     */
    public SupervisorOptional getNonVeterinarian() {
        return nonVeterinarian;
    }

    /**
     * Sets the value of the nonVeterinarian property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupervisorOptional }
     *     
     */
    public void setNonVeterinarian(SupervisorOptional value) {
        this.nonVeterinarian = value;
    }

    /**
     * Gets the value of the veterinarian property.
     * 
     * @return
     *     possible object is
     *     {@link VetSupervisorMirrorSupervisorOptional }
     *     
     */
    public VetSupervisorMirrorSupervisorOptional getVeterinarian() {
        return veterinarian;
    }

    /**
     * Sets the value of the veterinarian property.
     * 
     * @param value
     *     allowed object is
     *     {@link VetSupervisorMirrorSupervisorOptional }
     *     
     */
    public void setVeterinarian(VetSupervisorMirrorSupervisorOptional value) {
        this.veterinarian = value;
    }

}
