//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TitrationTimingAndDuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TitrationTimingAndDuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;choice>
 *             &lt;element name="MeasurementAdministrationTiming" type="{}MeasurementTiming"/>
 *             &lt;element name="MeasurementFrequency" type="{}MeasurementFrequencyTiming"/>
 *             &lt;element name="MeasurementInterval" type="{}MeasurementIntervalTiming"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;element name="MeasurementDuration" type="{}MeasurementDuration"/>
 *         &lt;element name="MeasurementDurationTrigger" type="{}MeasurementDurationTriggerTiming"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TitrationTimingAndDuration", propOrder = {
    "measurementAdministrationTiming",
    "measurementFrequency",
    "measurementInterval",
    "measurementDuration",
    "measurementDurationTrigger"
})
public class TitrationTimingAndDuration {

    @XmlElement(name = "MeasurementAdministrationTiming")
    protected MeasurementTiming measurementAdministrationTiming;
    @XmlElement(name = "MeasurementFrequency")
    protected MeasurementFrequencyTiming measurementFrequency;
    @XmlElement(name = "MeasurementInterval")
    protected MeasurementIntervalTiming measurementInterval;
    @XmlElement(name = "MeasurementDuration")
    protected MeasurementDuration measurementDuration;
    @XmlElement(name = "MeasurementDurationTrigger")
    protected MeasurementDurationTriggerTiming measurementDurationTrigger;

    /**
     * Gets the value of the measurementAdministrationTiming property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementTiming }
     *     
     */
    public MeasurementTiming getMeasurementAdministrationTiming() {
        return measurementAdministrationTiming;
    }

    /**
     * Sets the value of the measurementAdministrationTiming property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementTiming }
     *     
     */
    public void setMeasurementAdministrationTiming(MeasurementTiming value) {
        this.measurementAdministrationTiming = value;
    }

    /**
     * Gets the value of the measurementFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementFrequencyTiming }
     *     
     */
    public MeasurementFrequencyTiming getMeasurementFrequency() {
        return measurementFrequency;
    }

    /**
     * Sets the value of the measurementFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementFrequencyTiming }
     *     
     */
    public void setMeasurementFrequency(MeasurementFrequencyTiming value) {
        this.measurementFrequency = value;
    }

    /**
     * Gets the value of the measurementInterval property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementIntervalTiming }
     *     
     */
    public MeasurementIntervalTiming getMeasurementInterval() {
        return measurementInterval;
    }

    /**
     * Sets the value of the measurementInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementIntervalTiming }
     *     
     */
    public void setMeasurementInterval(MeasurementIntervalTiming value) {
        this.measurementInterval = value;
    }

    /**
     * Gets the value of the measurementDuration property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementDuration }
     *     
     */
    public MeasurementDuration getMeasurementDuration() {
        return measurementDuration;
    }

    /**
     * Sets the value of the measurementDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementDuration }
     *     
     */
    public void setMeasurementDuration(MeasurementDuration value) {
        this.measurementDuration = value;
    }

    /**
     * Gets the value of the measurementDurationTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementDurationTriggerTiming }
     *     
     */
    public MeasurementDurationTriggerTiming getMeasurementDurationTrigger() {
        return measurementDurationTrigger;
    }

    /**
     * Sets the value of the measurementDurationTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementDurationTriggerTiming }
     *     
     */
    public void setMeasurementDurationTrigger(MeasurementDurationTriggerTiming value) {
        this.measurementDurationTrigger = value;
    }

}
