//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransferType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransferType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TRANSFER TO PHARMACY"/>
 *     &lt;enumeration value="TRANSFER FROM PHARMACY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransferType")
@XmlEnum
public enum TransferType {


    /**
     * This is the requesting pharmacy has sent the transfer request and will be transferring in the prescriptions, i.e. the transfer to pharmacy.
     * 
     */
    @XmlEnumValue("TRANSFER TO PHARMACY")
    TRANSFER_TO_PHARMACY("TRANSFER TO PHARMACY"),

    /**
     * This is the pharmacy has received the transfer request and will be transferring out the prescriptions, i.e. the transfer from pharmacy.
     * 
     */
    @XmlEnumValue("TRANSFER FROM PHARMACY")
    TRANSFER_FROM_PHARMACY("TRANSFER FROM PHARMACY");
    private final String transferTypeValue;

    TransferType(String v) {
    	transferTypeValue = v;
    }

    public String value() {
        return transferTypeValue;
    }

    public static TransferType fromValue(String v) {
        for (TransferType c: TransferType.values()) {
            if (c.transferTypeValue.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
