//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.18 at 03:04:58 PM EST 
//


package gov.va.med.pharmacy.ncpdpmsgs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionDomain.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionDomain">
 *   &lt;restriction base="{}Code">
 *     &lt;enumeration value="SCRIPT"/>
 *     &lt;enumeration value="SPECIALIZED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransactionDomain")
@XmlEnum
public enum TransactionDomain {


    /**
     * NCPDP SCRIPT schema
     * 
     */
    SCRIPT,

    /**
     * NCPDP Specialized schema
     * 
     */
    SPECIALIZED;

    public String value() {
        return name();
    }

    public static TransactionDomain fromValue(String v) {
        return valueOf(v);
    }

}
